samples/CommunityToolkit.Maui.Sample/Pages/Base/BasePage.cs

For Maui preview 7 we don't have the `IPage` interface anymore.
you can see more info [here](https://github.com/dotnet/maui/pull/1875)

Removed IPage interface

---

azure-pipelines.yml

For PRs I now generate a version number like `1.0.0-build.18+1a2b3c4`. The number is `{current major version}-build{GitHub PR issue number}+{commit SHA}`.
I also hooked up a release that releases PR builds, with this version number, to a special PR nuget feed so people can easily try out new changes.
Additionally, to make people find the NuGets more easily I rename the Azure DevOps build name so that it shows up in the GitHub Checks, see:
Or check the actual checks box at the bottom of this PR :)

Add version number generation for PRs to pipeline

---

.editorconfig
azure-pipelines.yml
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
samples/CommunityToolkit.Maui.Sample/Pages/Extensions/ColorAnimationExtensionsPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Extensions/ColorAnimationExtensionsPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/Pages/Extensions/ExtensionsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Extensions/ExtensionsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/MainViewModel.cs
src/CommunityToolkit.Maui/Extensions/ColorAnimationExtensions.shared.cs
src/CommunityToolkit.Maui/Extensions/ColorAnmiationExtensions.shared.cs

Fixes #88 
Implemented Extension method, added Sample.
There seems to be a bug on Windows on some controls as their BackgroundColor doesn't get updated. I've filed a bug for that on the [MAUI repo](https://github.com/dotnet/maui/issues/3506).
I'm not sure if/how this can be unit tested properly. If you have any ideas about this, let me know.

Color to animation extension #88

---

src/CommunityToolkit.Maui.UnitTests/Converters/DateTimeOffsetConverter_Tests.cs
src/CommunityToolkit.Maui/Converters/ICommunityToolkitMultiValueConverter.shared.cs
src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MultiMathExpressionConverter.shared.cs
src/CommunityToolkit.Maui/Converters/VariableMultiValueConverter.shared.cs
src/CommunityToolkit.Maui/Extensions/MultiValueConverterExtension.shared.cs

This PR fixes a typo in the name `ICommunityToolkitMultiValueConverter`.
It was incorrectly named `ICommunityToolkitIMultiValueConverter`.

Fix `ICommunityToolkitMultiValueConverter` name typo

---

Directory.Build.props

This PR ensures that future PRs will continue to have properly formatted XML Documentation
Adds the following compiler warnings to `<WarningsAsErrors>` in `DirectoryBuild.props`:
- CS1573: Parameter has no matching param tag in the XML comment 
- CS1734: XML comment has a paramref tag, but there is no parameter by that name

Add Additional XML Warnings to `<WarningsAsErrors>` in `Directory.Build.props`

---

src/CommunityToolkit.Maui.UnitTests/Converters/DateTimeOffsetConverter_Tests.cs
src/CommunityToolkit.Maui/Converters/DateTimeOffsetConverter.shared.cs

DateTimeOffsetConverter ConvertBack ignores current culture. For my region (Ukraine) the current offset is +3 in the summertime, and +2 in the wintertime. To fix the issue we need to pass Culture.Calendar parameter to the DateTimeOffset.
before:
after:

Fix DateTimeOffset failed tests

---

Directory.Build.props
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj

Moves the `EnforceCodeStyleInBuild` introduced in #220 out to the common `Directory.Build.props` file to make sure it isn't missed on new projects.

Move EnforceCodeStyleInBuild out to Directory.Build.props

---

src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.android.cs

Use TrySetResult to prevent InvalidOperationException when the underlying Task is already in one of the three final states: RanToCompletion, Faulted, or Canceled.
- Fixes #266

Use TrySetResult to prevent InvalidOperationException

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj

This PR fixes the `System.TypeLoadException` for `GridLayout` causing the Gallery Pages to appear blank on the Windows Sample App:
> System.TypeLoadException: 'Could not load type 'Microsoft.Maui.Controls.GridLayout' from assembly 'Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
The error was caused by an old version of `CommunityToolkit.Maui.Markup`. Updating to `CommunityToolkit.Maui.Markup-pre7` resolves the issue.

Fix `GridLayout` `System.TypeLoadException` on Windows for `CommunityToolkit.Maui.Sample`

---

samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Base/BasePage.cs

.NET MAUI Preview 13 introduced `Device.MacCatalyst`. Previously, `Device.RuntimePlatform ==  Device.iOS` was true on `net6.0-maccatalyst`
This PR updates the Sample App to differentiate between `Device.iOS` and `Device.MacCatalyst`.

Update Sample App for MacCatalyst

---

Directory.Build.props
src/CommunityToolkit.Maui.UnitTests/BaseTest.cs
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Converters/ImageResourceConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/IsListNotNullOrEmptyConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/IsListNullOrEmptyConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/IsStringNotNullOrEmptyConverter_Tests.cs
src/CommunityToolkit.Maui/Behaviors/EventToCommandBehavior.shared.cs
src/CommunityToolkit.Maui/Converters/BaseConverterOneWay.shared.cs
src/CommunityToolkit.Maui/Converters/EqualConverter.shared.cs
src/CommunityToolkit.Maui/Converters/ImageResourceConverter.shared.cs
src/CommunityToolkit.Maui/Converters/IsListNotNullOrEmptyConverter.cs
src/CommunityToolkit.Maui/Converters/IsListNullOrEmptyConverter.cs
src/CommunityToolkit.Maui/Converters/IsStringNotNullOrEmptyConverter.shared.cs
src/CommunityToolkit.Maui/Converters/ItemSelectedEventArgsConverter.shared.cs
src/CommunityToolkit.Maui/Converters/ItemTappedEventArgsConverter.shared.cs
src/CommunityToolkit.Maui/Converters/NotEqualConverter.shared.cs

> Note: This PR targets the `feature/not-supported-exception` branch, aka #296. It does not target the `main` branch
This PR adds `null` support for `BaseOneWayConverter<TFrom, TTo>`.
Adding support for `null` enables us to use nullable generics, eg `<TFrom?, TTo?>` which then introduces the possibility to update the following converters from `BaseOneWayConverter` to `BaseOneWayConverter<TFrom, TTo>`:
- `public class ImageResourceConverter : BaseOneWayConverter<TFrom, TTo>`
- `public class IsStringNotNullEmptyConverter : BaseOneWayConverter<TFrom, TTo>`
- `public class IsListNotNullOrEmptyConverter : BaseOneWayConverter<TFrom, TTo>`
- `public class IsListNullOrEmptyConverter : BaseOneWayConverter<TFrom, TTo>`
- `public class ItemSelectedEventArgsConverter : BaseOneWayConverter<TFrom, …

Add Null Support for BaseOneWayConverter<TFrom, TTo> 

---

src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToColorConverter_Tests.cs
src/CommunityToolkit.Maui/Converters/ColorToColorConverters.shared.cs

This PR implements unit tests for the ColorToColor Converters found in `ColorToColorConverters.shared.cs`
- Fixes #52 
I've also added `ArgumentNullException.ThrowIfNull(value);` to each Converter. Even though we have `<nullable>Enable</nullable>`, devs who do not have nullable enabled may still try to pass in `null` via the public API.

Add `ColorToColor` Converter Unit Tests

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/ProgressBarAnimationBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/ProgressBarAnimationBehaviorPage.xaml.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/MaskedBehavior_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/ProgressBarAnimationBehavior_Tests.cs
src/CommunityToolkit.Maui/Behaviors/BaseBehavior.shared.cs
src/CommunityToolkit.Maui/Behaviors/ProgressBarAnimationBehavior.shared.cs

This PR adds Unit Tests for `ProgressBarAnimationBehavior`
- Fixes #48 
I've also included a few changes to `ProgressAnimationBehavior`:
- Rename `ProgressBarAnimationBehavior.AnimateProgress` to `ProgressBarAnimationBehavior.Progress` 
- This property mirrors and directly changes `ProgressBar.Progress`
- This naming change should improve discoverability for devs familiar with `ProgressBar.Progress` who are seeking to bind to `ProgressBarAnimationBehavior.ProgressProperty`
- Added the bindable property `ProgressBarAnimationBehavior.Easing` 
- This new property allows users to change the `Easing easing` of the `ProgressTo` animation
- Added the bindable property `ProgressBarAnimationBehavior.Length` 
-  This new property allow users to change the `uint length` of the `ProgressTo` animation …

Add `ProgressBarAnimationBehavior` Unit Tests

---

src/CommunityToolkit.Maui.Core/Extensions/ColorConversionExtensions.shared.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/ProgressBarAnimationBehavior_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToBlackKeyConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToByteAlphaConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToByteBlueConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToByteGreenConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToByteRedConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToDegreeHueConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToPercentCyanConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToPercentMagentaConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/ColorToPercentYellowConverter_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/ColorConversionExtensions_Tests.cs
src/CommunityToolkit.Maui/Converters/ColorToComponentConverter.shared.cs

This PR adds Unit Tests for the `ColorTo*` Converters.
- Fixes #53 
- Added `ArgumentNullException.ThrowIfNull` to `ColorConversionExtensions` APIs
- Update `ProgressBarAnimationBehavior_Tests.cs`
- This test was randomly timing out due to a race condition (including in our CI pipeline)
- Added `Timeout = 5000` to `ProgressBarAnimationBehavior_Tests.cs`
- Lowered the longest test's time duration from `1500` `500`

Add `ColorTo*` Unit Tests

---

.runsettings
azure-pipelines.yml
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj

Adds code coverage tab with the report:
https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=69366&view=codecoverage-tab

Calculate and display code coverage report

---

src/CommunityToolkit.Maui.UnitTests/Converters/ListToStringConverter_Tests.cs
src/CommunityToolkit.Maui/Converters/ListToStringConverter.shared.cs

This PR updates `ListToStringConverter`, to ensure ``public string Separator { get; set; }` cannot be `null`. 
In the `ConvertFrom` logic, we can then remove the unused `??` and adding a comment explaining that the `object? parameter` takes precedence over `public string Separator { get; set; }`.
This PR also updates the XML Documentation for `public string Separator { get; set; }` to better help the user understand the order of precedence between `object? parameter` and `public string Separator { get; set; }`.
These updates are inspired by the documentation for `ListToStringConverter`: https://github.com/MicrosoftDocs/CommunityToolkit/blob/73bd78afad79aa07c9c8329119ca45b5688d54d4/docs/maui/converters/list-to-string-converter.md

`ListToStringConverter`: Remove Unused Null Coalescing Operator + Update XML Documentation

---

src/CommunityToolkit.Maui.UnitTests/Views/PopupTests.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
src/CommunityToolkit.Maui/Views/WrapperControl.windows.cs

This PR ensures that `Popup.Color` cannot be set to `null`.
Because `Popup.Color` can be used as a bindable property, I implemented the `null` validation on `public static readonly BindableProperty ColorProperty` to ensure validation also happens if a `null` value is passed in via a binding.
I also added `ArgumentNullException.ThrowIfNull` to `WrapperControl` which is used by `Popup` on Windows.

Add `Popup.Color` Null Validation

---

src/CommunityToolkit.Maui.Core/Primitives/Defaults.shared.cs
src/CommunityToolkit.Maui.UnitTests/Alerts/Snackbar_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Alerts/Toast_Tests.cs
src/CommunityToolkit.Maui/Alerts/Snackbar/SnackBar.shared.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.shared.cs

This PR adds `null` validation checks for the following:
- `Snackbar.Text `
- `Snackbar.ActionButtonText `
- `Toast.Text `
This PR also added `ArgumentNullException` Unit Tests for these properties in `Snackbar_Tests` and `Toast_Tests`.
I added Unit Tests to verify both `Snackbar` and `Toast` default values.
I also added `[EditorBrowsable(EditorBrowsableState.Never)]` to `CommunityToolkit.Maui.Core.Defaults`

Add `Null` Validation to `Toast` and `Snackbar`

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs

This PR updates the Sample App to use `CommunityToolkit.Maui.Markup` v1.0.0-pre9.
It also adds `WeakEventManager` to `MauiPopup.PopoverDelegate.PopoverDismissedEvent` now that `WeakEventManager` lives in the `Microsoft.Maui` namespace.
(`WeakEventManager ` was previously in the `Microsoft.Maui.Controls` namespace).

Update Sample App to `CommunityToolkit.Maui.Markup` v1.0.0-pre9

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Views/CsharpBindingPopupViewModel.cs
samples/CommunityToolkit.Maui.Sample/Views/Popups/ButtonPopup.xaml
samples/CommunityToolkit.Maui.Sample/Views/Popups/MultipleButtonPopup.xaml
samples/CommunityToolkit.Maui.Sample/Views/Popups/NoOutsideTapDismissPopup.xaml
samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml
samples/CommunityToolkit.Maui.Sample/Views/Popups/ToggleSizePopup.xaml
src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs

There's no specific issue for this _fix_, this PR just removed the word `native` from our samples and code base... Also fixed some xaml indentation.
- Fixes #

Changed the usage of `native` word to one that fits better

---

src/CommunityToolkit.Maui.Core/Handlers/Popup/PopupHandler.shared.cs

On `Core` we should use the abstractions when it's possible. During the implementation of `PopupView` we missed a small detail, we're using `PropertyMapper` instead of `IPropertyMapper`
- Fixes #368

Changed PopupHandler.PropertyMapper -> IPropertyMapper

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj

I commented out the code in csproj that creates a copy of generated files into the `obj` folder. Now that those files don't exist we shouldn't hit that problem anymore.
I didn't delete the code, to help devs that may work on our SG project, so they just need to uncomment those lines.
**It works on my machine™**
- Fixes #418

Fixed issue with windows LongPath

---

src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorTo_Tests.cs

This PR makes sure that SG will generate new extension methods for brand new controls. If the control is already inherited from a .NET MAUI type that implements `ITextStyle` and `IAnimatable` (like `Picker`), we don't generate a new extension method.
```csharp
class MyPicker<T> : Picker 
{
}
void Bla() 
{
var myPicker = new MyPicker<string>();
// This will use the method generated for the Picker control
myPicker.TextColorTo(Colors.Blue);
}
```
This will reduce the amount of generated code improve the final app size and will cover more scenarios, like generic ones.
- Fixes #409

Avoid code generation for types that can use existing extension methods

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs

Make sure to change the correct backgroundColor View on Apple platform. And make sure to call the `SetBackgroundColor` when the `View` isn't `null`.
- Fixes #450

Fix background issue on apple platform

---

src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorTo_Tests.cs

- Added extensions to serialize generic type arguments 
- Using new extensions in TextColorToGenerator 
#409 
- Fixes #409

Handle Generic Implementations of `ITextStyle` by TextColorToGenerator 

---

src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs

This PR fixes how we calculate the size before we're using the platform values which seems to not be the best approach, so now we're using the xplat values, and looks like that fixes the issue.
This fixes one of the bugs in the related issue.
- Related to #428 
Main (the wrong behavior):
This PR (the expected behavior):

Fixed the size calculation for iOS

---

src/CommunityToolkit.Maui.Core/Extensions/MathExtensions.shared.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/MathExtensions_Tests.cs

This PR fixes the Popup position on screen and looks like also fixed the ShellContent issue (when we present a popup the ShellContent became blank).
A note is that for macOS the popup in the `X` position is offset a little bit to the right, @PureWeen and I couldn't figure out why that happen, but it's way better than before.
Thanks, Shane for all the help❣️
- Fixes #466
- Fixes #463
- Fixes #428
Main:
This PR:

Fix popup position

---

.github/dependabot.yml
azure-pipelines.yml
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj

Fail pipeline if has any vulnerability
- Fixes #493

[Bug] CI Pipeline Does Not Fail when Vulnerable Dependencies Found #493

---

.github/fabricbot.json

Proposals should be closed automatically by `msftbot` when moved to the `Closed` or `Completed` column in our [New Feature Proposals Project Board](https://github.com/CommunityToolkit/Maui/projects/1).
Due to a bug in the Boolean logic, `msftbot` has been incorrectly reopening Proposals that should remain closed:
```
// Previous Logic (with bug)
(`proposal` label || On New Feature Proposal project board || Title contains `[Proposal]`)
&& (!IsOpen)
&& (![Is in Closed Column] || ![Is in Completed Column]) // BUG: This would always resolve to `true` because the Proposal could never be in both columns simultaneously
// Previous Logic (with bug)
(`proposal` label || On New Feature Proposal project board || Title contains `[Proposal]`)
&& (!IsOpen)
&& !([Is in Closed Column] || [Is in Completed …
```

Fix MSFTBOT Bug Causing it to Reopen Completed/Closed Proposals

---

src/CommunityToolkit.Maui.Analyzers/UseCommunityToolkitInitializationAnalyzer.cs

This adds one more level to make sure the analyzer will not get confused by our `UseMCT` being a comment.
```csharp
builder
.UseMauiApp<App>()
.ConfigureLibrary()
//.UseMauiCommunityToolkit()
.ConfigureFonts();
```
- Fixes #501

Make sure the string `UseMauiCommunityToolkit` isn't a comment

---

src/CommunityToolkit.Maui.UnitTests/Behaviors/EmailValidationBehavior_Tests.cs
src/CommunityToolkit.Maui/Behaviors/Validators/EmailValidationBehavior.shared.cs

This PR assigns `InputView.Keyboard = Keyboard.Email` when `EmailValidationBehavior` is attached to a control and the default keyboard is in use: 
```cs
/// <inheritdoc /> 
protected override void OnAttachedTo(VisualElement bindable)
{
// Assign Keyboard.Email if the user has not specified a specific Keyboard layout
if (bindable is InputView inputView && inputView.Keyboard == Keyboard.Default)
{
inputView.Keyboard = Keyboard.Email;
}
base.OnAttachedTo(bindable);
}
```
- Fixes #545 
~Documentation will also need to be updated.~
I've also updated `[EmailValidationBehavior_Tests.cs](https://github.com/CommunityToolkit/Maui/pull/547#diff-c8d8498486665de32295100cda8b342b39eeebedad3fea646fbd201e05a431f3)` to reflect this new expected behavior.

`EmailValidationBehavior`: Assign `Keyboard.Email` when Attached

---

.editorconfig
Directory.Build.props
samples/CommunityToolkit.Maui.Sample/Pages/Views/DrawingViewPage.xaml.cs
src/CommunityToolkit.Maui.Analyzers.CodeFixes/Properties/AssemblyInfo.cs
src/CommunityToolkit.Maui.Analyzers.CodeFixes/UseCommunityToolkitInitializationAnalyzerCodeFixProvider.cs
src/CommunityToolkit.Maui.Analyzers/Properties/AssemblyInfo.cs
src/CommunityToolkit.Maui.Analyzers/UseCommunityToolkitInitializationAnalyzer.cs
src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.shared.cs
src/CommunityToolkit.Maui.Core/Views/Snackbar/PlatformSnackbar.macios.cs
src/CommunityToolkit.Maui.Core/Views/Toast/PlatformToast.macios.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/IconTintColorBehavior_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/ImpliedOrderGridBehavior_Tests.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/SetFocusOnEntryCompleted_Tests.cs
src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.macios.cs
src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.shared.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.android.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.macios.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.shared.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.windows.cs
src/CommunityToolkit.Maui/Behaviors/UserStoppedTypingBehavior.shared.cs
src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpression.shared.cs

This PR adds the following rules:
- `.editorconfig`
- CA1001: Type owns disposable field(s) but is not disposable
- Ensures that we continue to implement `IDisposable` correctly
- CA1822: Member does not access instance data and can be marked as static
- Improve performance to avoid unnecessary stack allocations
- CA1050: Declare types in namespaces
- Ensures each file has a namespace declared
- CA2016: Forward the 'CancellationToken' parameter methods that take one
- Ensures we properly propagate `CancellationToken`
- CA2208: Method passes parameter as the paramName argument to a ArgumentNullException constructor. Replace this argument with one of the method's parameter names. Note that the provided parameter name should have the exact casing as declared on the method.
-  Ensures we …

Add Additional Rules to `.editorconfig`

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.windows.cs

Clean up the `FlyoutContext` property, so the flyout doesn't appear on right-click.
Thanks to @u1-kino  for sharing the solution
- Fixes #568

Clean up the ContextFlyout property

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ByteArrayToImageSourceConverterViewModel.cs

To demonstrate best practices for .NET MAUI apps that utilize HttpClient, this PR replaces the following NuGet Package:
- `Microsoft.Extensions.Http` -> [`Microsoft.Extensions.Http.Polly`](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly)
- (`Microsoft.Extensions.Http.Polly` includes a dependency on `Microsoft.Extensions.Http`)
Because .NET MAUI supports dependency injection, we can leverage `Microsoft.Extensions.Http.Polly` to add automatic error handling policies. In the updated code below, when HttpClient fails it will now automatically retry to connect to the URL 3 times using an exponential backoff of 2<sup>n</sup> seconds. This is ideal for flaky mobile internet connections where a user's device may switch cellular towers or lose a Wifi connection.
```cs …
```

[CommunityToolkit.Maui.Sample] Add `Microsoft.Extensions.Http.Polly` and implement `.AddTransientWithShellRoute()`

---

src/CommunityToolkit.Maui.Core/Handlers/DrawingView/DrawingViewHandler.shared.cs

The order of mapping properties is important. Lines should be mapped last
- Fixes #649

[BUG] GetImageStream wrong when lines populated from code #649

---

samples/CommunityToolkit.Maui.Sample/Pages/ImageSources/GravatarImageSourcePage.xaml

Sample app was using SemanticProperties.Description inside the GravatarImageSource - SemeanticProperties.Description is an AttachedProperty for a VisualElement. this was causing the sample app to crash on Windows
Fixes issue with Sample app crashing on Windows.
- Fixes #655

Moved SemanticProperites.Description setting out of ImageSource

---

src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs

Remove the MauiContext from the equation. Not sure why, but the popup.Handler.MauiContext isn't equal to popup.Anchor.Handler.MauiContext, and that was causing the issue.
- Fixes #682

Removed the MauiContext from ToPlatform call

---

samples/CommunityToolkit.Maui.Sample/Pages/ImageSources/GravatarImageSourcePage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/ImageSources/GravatarImageSourcePage.xaml.cs
src/CommunityToolkit.Maui/Views/AvatarView.shared.cs

Added clipping offset for all platforms, other than Windows.
- Fixes #646 
Tested and verified on platforms - 
This fix must be tested on **ALL** platforms, as it is an issue for different platforms.

FIX: AvatarView clipping on Android isn't applied correctly

---

src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorToTests.cs

- Fixes #719 
This PR updates the Unit Tests to test this new code by moving `public interface ISomeInterface` into its own unique namespace.
This PR also removes `bool isFirstConstraint`, replacing `if(!isFirstConstraint)` with `if(constraints.Length > 0)`.

For Source Generators, Ensure `GetGenericTypeConstraintsAsString` Includes Namespace for Type

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs
src/CommunityToolkit.Maui/Converters/ByteArrayToImageSourceConverter.shared.cs
src/CommunityToolkit.Maui/Converters/ImageResourceConverter.shared.cs
src/CommunityToolkit.Maui/Converters/ItemTappedEventArgsConverter.shared.cs
src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MultiMathExpressionConverter.shared.cs
src/CommunityToolkit.Maui/Converters/SelectedItemEventArgsConverter.cs
src/CommunityToolkit.Maui/Converters/TextCaseConverter.shared.cs

This PR implements the [expanded scope of the `nameof` operator in C# 11](https://learn.microsoft.com/dotnet/csharp/whats-new/csharp-11#extended-nameof-scope):
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#extended-nameof-scope
It is updating syntactic sugar and does not modify any functionality.

[Housekeeping] Implement Expanded C# 11 `nameof` Scope

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.android.cs
src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs
src/CommunityToolkit.Maui.MediaElement/PlatformView/MauiMediaElement.android.cs
src/CommunityToolkit.Maui.MediaElement/PlatformView/MauiMediaElement.windows.cs
src/CommunityToolkit.Maui.MediaElement/PlatformView/MediaManager.windows.cs

This PR fixes MediaElement's memory leak on Android and Windows.

Fix `MediaElement` memory leak

---

src/CommunityToolkit.Maui.MediaElement/PlatformView/MediaManager.android.cs

When streaming from an URL it is possible that ExoPlayer does not receive the information necessary to set the duration of a title. 
If this is the case, the ExoPlayers' duration property is set to TIME_UNSET which is a constant defined as Long.MIN_VALUE +1 (-9223372036854775807). 
However, the current MediaManager implementation for Android defined in **MediaManager.android.cs** handles the **OnPlayerStateChanged** event by setting the mediaElements' duration property if the playback state equals StateReady. It does so by converting the underlying players' duration property to  a TimeSpan.
In case ExoPlayers' duration property equals TIME_UNSET in that moment, the call to TimeSpan.FromMilliseconds results in an OverflowException.
More specifically:
**System.OverflowException:** 'TimeSpan …

Fix MediaElement Androids' player.Duration OverflowException and PlaybackState

---

src/CommunityToolkit.Maui.Core/Interfaces/IToast.shared.cs

While creating a video for Toast I noticed that this enum only specified "short" and "long" which isn't very meaningful to the user. Added the actual length to the description for this.

Update ToastDuration options documentation with actual duration

---

src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorToTests.cs

This PR changes generated classes for .NET MAUI controls, i.e.  code generated for `Microsoft.Maui.Controls.*` by `TextColorTo`, from `public` to `internal`.
The bug in https://github.com/CommunityToolkit/Maui.Markup/issues/158 is caused by two matching public classes being generated in both the .NET MAUI library (eg `net7.0-ios`) and the referenced class library (e.g. `net7.0`).
```
📦MyMauiSolution
┣ 📂MyMauiApp
- <TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
┗ 📂MyLibrary
- <TargetFramework>net7.0</TargetFramework>
```
- Fixes https://github.com/CommunityToolkit/Maui/discussions/756#discussioncomment-4125731

Make `TextColorTo` Generated Classes for .NET MAUI Controls Internal

---

src/CommunityToolkit.Maui.UnitTests/Views/DrawingView/DrawingViewTests.cs
src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs

I've change the `LinesProperty` of the `DrawingView` to use a `defaultValueCreator` delegate instead of a `defaultValue`. The default value is a reference `new ObservableCollection<IDrawingLine>()` in a static create function. Hence it was a collection shared over all `DrawingView`s in a MAUI app.
These kind of situations are AFAIK _exactly_ why the `defaultValueCreator` delegate exists.
I haven't provided samples, but I did add a unittest to verify that `new DrawingView().Lines` no longer share a reference.
I haven't changed any documentation, as it doesn't conflict. The documented use coincidentally worked, because it uses either a `Lines = { Binding MyLines }` in XAML and initialises with a `Lines = new ObservableCollection<IDrawingLine>()` in C#. I think the approach where by default …

Do not use shared default value for LinesProperty

---

.github/ISSUE_TEMPLATE/bug_report_template.yml
CONTRIBUTING.md

This PR adds our guideline for opening a bug report.
There's no issue, it's just a housekeeping ♻️PR

Update Contributing guide with opening a bug step ♻️

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/IconTintColorBehaviorViewModel.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.ios.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.shared.cs

This PR improves the binding logic inside the Behavior and adds a sample showing how to use it in MVVM fashion way.
- Fixes #775

Improve bindings on tintcolor

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
src/CommunityToolkit.Maui/Views/Expander/Expander.macios.cs
src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs
src/CommunityToolkit.Maui/Views/Expander/Expander.windows.cs

This PR adds the workaround for Expander and collections but in an indirect way. This way we allow users to handle that by themselves and also provide a _default_ workaround they can opt-in to apply.
This can unblock users and provide a workaround that can easily be deleted as soon as this issue is solved (on .net Maui side maybe)
- Fixes #742

Alternative to #751

---

src/CommunityToolkit.Maui.UnitTests/Behaviors/StatusBarBehaviorTests.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/StatusBar/StatusBarBehavior.shared.cs

Check Activity for null on PropertyChanged.
OnPropertyChanged is called before OnAttachedTo. However, OnAttachedTo called later and set the StatusBar color. Then if any of the properties are changed OnPropertyChanged is called and updates the value.
- Fixes #685, #880

StatusBar. Check for Android Activity for null.

---

src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.shared.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.shared.cs
src/CommunityToolkit.Maui/Alerts/Toast/Toast.windows.cs
src/CommunityToolkit.Maui/Extensions/ToastNotificationExtensions.windows.cs

Update Toast Windows to use the new API AppNotificationManager as Microsoft recommends: https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/adaptive-interactive-toasts?tabs=appsdk

Use AppNotificationManager instead of ToastNotificationManager

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/CompareConverterPage.xaml

Set background color
- Fixes #796

Fix Label background color in CompareConverter Sample #796

---

azure-pipelines.yml

This updates our build pipeline so that we can release `MediaElement` separately from the main package. It adds these things:
* Separate variable for setting the MediaElement version
* Only if the tag does _not_ end with `-mediaelement` (case insensitive), we assume that it's a release for the main package
* Only if the tag _does_ end with `-mediaelement` (case insensitive), we assume that it's a release for `MediaElement`
The rest of the process stays pretty much the same. In Azure DevOps I will create separate releases for each of these packages. The artifacts are still always published because we also use this flow for the pull requests, that will be fixed by a separate pipeline in Azure DevOps to release the right bits.

Update build pipeline to enable separate MediaElement release

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

A couple of small fixes for MediaElement.
* Removes higher WindowsAppSDK version dependency fixing a build error in your .NET MAUI app when consuming
* Fix `ShouldAutoPlay` on Android
* Proper `CurrentState` reporting on Windows when the `Speed` property is used to play and pause
* Fixes #927 
* Fixes #926 
* Fixes #921 
* Closes #925

Various MediaElement fixes

---

samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FileSaverPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Essentials/FolderPickerPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FileSaverViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FolderPickerViewModel.cs
src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.macios.cs

Fix FolderPicker Error when trying to open a second time on MacCatalyst

---

src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs

For iOS 16 and macOS 13 and up we have to do a little trickery to make the platform transport controls show up. It seems that this trickery only works, but also only is necessary, when you use .NET MAUI Shell.
This PR relaxes the code a little bit so that it doesn't start throwing exceptions but just skips over this part. From testing this seems to work in both Shell and non-Shell scenarios now.
- Fixes #985

Relax ViewController detection for iOS MediaElement to enable non-Shell usage

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs

Changes the order of the dispose calls for Windows to see if that fixes issues when cleaning up resources 
- Fixes #962

Fix disposal of MediaElement for Windows

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs

When a `MediaElement` is created on iOS, find the parenting `UIViewController` and pass that down. This is needed on iOS to prevent issues with `AVPlayerViewController`
- Fixes #985

Provide parent view controller to MediaElement iOS

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/DrawingViewPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/DrawingViewViewModel.cs
src/CommunityToolkit.Maui.Core/Interfaces/IDrawingView.shared.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.android.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.net.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.tizen.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.windows.cs
src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs

Fix DrawingView ImageSize

---

samples/CommunityToolkit.Maui.Sample/Pages/Layouts/StateContainerPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Layouts/StateContainerPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/StateContainerViewModel.cs
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Layouts/StateContainerTests.cs
src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainer.shared.cs
src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs

Instead of throwing exceptions, just return. The animation operation is canceled but we still can continue going to the next state.
- Fixes #942, #1027

StateContainer, Add `ChangeStateWithAnimation()`

---

src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs

FileMode.OpenOrCreate does not automatically truncate files.
This fix truncates files to ensure that junk data does not appear at the end of a newly saved file if the data being written is shorter than data present in a previously existing file.
- Fixes #1049

FileSaver does not truncate existing files

---

azure-pipelines.yml
global.json

This PR increases the minimum .NET Dependency listed in `global.json` + `azure-pipelines.yml` to .NET v7.0.200.
This fixes an oversight after we [increased the .NET MAUI version to v7.0.59 to support `CollectionView` in `Expander`](https://github.com/CommunityToolkit/Maui/commit/4adb6c94d1f78bb56f5bb6fc09d864f64f1dc31d#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5).
The Issue linked below demonstrates that .NET MAUI Community Toolkit no longer supports .NET v7.0.100 (we should've updated these values in `global.json` and `azure-pipelines.yml` in that PR).
We've also noted the Breaking Change in our [Release Notes for v5.0.0](https://github.com/CommunityToolkit/Maui/releases/tag/5.0.0) that .NET MAUI 7.0.59 is required which is included in .NET 7.0.200.
- Fixes …

[Housekeeping] Increase Toolkit .NET Version to v7.0.200

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FolderPickerViewModel.cs
src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.macios.cs
src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.macios.cs
src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.windows.cs

Create a temp folder and keep original filename
- Fixes #1059

Fixes FileSaver filename on Apple

---

Directory.Build.props

This PR enables `AccelerateBuildsInVisualStudio`, recently introduced in Visual Studio v17.5:
https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md
> The feature was added in 17.5 and is currently opt-in. It applies to SDK-style .NET projects only. It is simple to try, and in most cases will improve build times. Larger solutions will see greater gains.
>
>
> Visual Studio uses MSBuild to build .NET projects. There is some overhead associated with calling MSBuild to build each project, so Visual Studio uses a "fast up-to-date check" (FUTDC) to avoid calling MSBuild unless needed. This FUTDC can quickly determine if anything has changed in the project that would cause a build to be required. For more information, see [Up-to-date …

[Housekeeping] Enable `AccelerateBuildsInVisualStudio`

---

azure-pipelines.yml
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.windows.cs

This PR fixes a `NullReferenceException` that may arise when disposing a `Popup` on Windows.
- Fixes #1105

Fix `MauiPopup.windows.cs` `NullReferenceException`

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.android.cs
src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.tizen.cs
src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.tizen.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

This PR is a recommendation to update the existing PR #1015.
This PR also includes formatting fixes to `MediaManager.Tizen.cs`:
- Use `or` to evaluate multiple `enum` states
- Consolidate methods, keeping `public` methods grouped together, `protected` methods grouped together, etc

Promote `MediaManager.PlatformSeek()` from `void` to `ValueTask`

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/EventToCommandBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/EventToCommandBehaviorViewModel.cs

1134 Update samples

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs

If you rotate the screen while the Popup is displayed, the Popup will be displayed 
in an unintended position. This PR ensures that the popup appears in the correct 
position after screen rotation. 
This issue was resolved by overriding MauiPopup's ViewWilTransitionToSize method and 
calling the PopupExtension's SetSize and SetLayout methods after rotation. 
Because the anchor is not set again after screen rotation. By setting this anchor again, 
the Popup will be displayed at the intended location.
[MauiPopup.macios.cs]
public override void ViewWillTransitionToSize(CGSize toSize, IUIViewControllerTransitionCoordinator coordinator)
{
coordinator.AnimateAlongsideTransition((IUIViewControllerTransitionCoordinatorContext obj) => {			
// Before screen rotate
}, …

Fix Issue #1238

---

src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs

Because the coordinates were provided without quotes, comma characters would end up in the coordinates and mess up the JavaScript syntax causing weird locations to be used.
In addition, the clicking of a Pin would not work. Also added  the InfoWindow and the click of said window.
With this PR, all of these are fixed.
Fixes #1255

[MAPS] Fix location coordinates and Pin/InfoWindow click

---

src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs

By providing the coordinates as a string there would still be an offset to where the coordinates should actually be placed and where they ended up on the map.
This change removes the JavaScript quotes and instead does a `ToString(CurrentCulture.InvariantCulture);` on the C# objects to the decimal separator is not converted to a comma and will not interfere with the JavaScript syntax.
Follow up from #1257

Fix coordinate usage on Windows Maps

---

src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs
src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs
src/CommunityToolkit.Maui/Layouts/DockLayout.shared.cs

When properties are updated affecting layout, `InvalidateMeasure` should be called to trigger the layout to happen, normally called via a propertyChanged notification. This PR adds that for `DockLayout`. The `InvalidateMeasure` method added here is similar to what's called for Grid properties in the MAUI repo.
- Fixes #1250
Note that I attempted adding unit tests, but none of my attempts were able to catch the behavior difference when `InvalidateMeasure` is called. This may be something normally done by "device tests" in the MAUI repo. So I ended up just testing manually against my test repo, which all looked good.

Call InvalidateMeasure on DockLayout when properties change affecting layout

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/StateContainerViewModel.cs
src/CommunityToolkit.Maui.UnitTests/Layouts/StateContainerTests.cs
src/CommunityToolkit.Maui/Layouts/StateContainer/StateContainerController.shared.cs

This PR removes the `VerticalStackLayout` from the `StateContainer`.
.NET MAUI has [different behavior than Xamarin.Forms](https://github.com/dotnet/maui/issues/8888) for `StackLayout`. In .NET MAUI, `VerticalStackLayout` expands to the size of its children. When the children require more space than is available on the screen, `VerticalStackLayout` will continue to "display" the additional `View` below the visible area on the screen.
The example below uses a `ScrollView` inside of `StateContainer`. When `StateContainerController` places the `ScrollView` inside of a `VerticalStackLayout`, it does not scroll because the size of the `VerticalStackLayout` extends past the bottom of the screen. 
| `StateContainer` with `VerticalStackLayout` | `StateContainer` without `VerticalStackLayout` …

Remove `VerticalStackLayout` from `StateContainerController`

---

src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs

- Fixes #1256
Turned out that when you define both width and height it works, but if only one of them it crashes. After research i found that it allows you to set 0/Nan value to width or height if other parameter is not 0/Nan. My first idea was to just replace OR with AND but i'm not sure if there can be any edge cases. So i replaced this check for individual values.

Fix Issue #1256

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.windows.cs

Added a handler to dispose of the `PlatformView` at the right moment.
- Fixes #1245

Fix dispose on MediaElement on Windows

---

src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs

This change should prevent "ambiguous reference" error to occur when other packages are included in a MAUI project that provide their own Color objects.
Examples of such libraries are SixLabors.ImageSharp.
In the source code generator use a fully qualified namespace to the Color object, so `Color` is changed into `Microsoft.Maui.Graphics.Color`.
No tests added, as I don't think we can test for such a change. No documentation change required either. No samples for the fix here (not sure how to test).
- Fixes #1331

Use fully qualified namespace for Color reference in TextToColorGenerator

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs

Fixes #1333 IconTintColorBehavior causes image not to load on Windows 
Fixed issue with OnImageOpened

fix  IconTintColorBehavior  for Windows

---

Directory.Build.props
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.android.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.shared.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.tizen.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.windows.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj

This PR adds a new Roslyn Analyzer:  [MemoryAnalyzers](https://github.com/jonathanpeppers/memory-analyzers), a set of Roslyn C# code analyzers for finding memory leaks in iOS and MacCatalyst applications, created by @jonathanpeppers on Microsoft's .NET MAUI team.
The .NET MAUI team adopted `MemoryAnalyzers`, adding it to their code base in this PR last week: https://github.com/dotnet/maui/pull/16346/files
This PR also implements updates to our code base where `MemoryAnalyzers` found potential memory leaks.
I've also added `WarningsAsErrors` for the current 3 warnings surfaced by `MemoryAnalyzer` to ensure future PRs don't accidentally introduce new memory leaks: `MA0001`, `MA0002` and `MA0003`

Add `MemoryAnalyzer` roslyn analyzer

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs

Pre-initialized the Volume and Muted properties of the AVPlayer object so the video can set to start muted or under a specific volume. This issue occurs only when initializing the Media Element on the page.
**How to test this patch**
1. Open the `samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml` file, and add `ShouldMute="True"` property on the following XAML element:
```xml
<toolkit:MediaElement
x:Name="mediaElement"
ShouldAutoPlay="True"
Source="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
MediaEnded="OnMediaEnded"
MediaFailed="OnMediaFailed"
MediaOpened="OnMediaOpened"
PositionChanged="OnPositionChanged"
StateChanged="OnStateChanged"
SeekCompleted="OnSeekCompleted"/>
```
2. Run the sample app and go to Media …

[MediaElement] Pre-initialize the Player Volume and Muted Properties

---

Directory.Build.props
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.android.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.macios.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.shared.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.tizen.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.windows.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj

This reverts PR #1371.
After review from [Jonathan Peppers raised concerns around missing unit tests on PR #1371](https://github.com/CommunityToolkit/Maui/pull/1371/files/75386fb41d957a739419704caea417e538e98a96#diff-ce1cac33c2cb0a6f0ffc172a4aef7135ec91135c1387186d2b816f8801529919), it's best that we revert this PR until we have implemented Device Unit Testing (ie unit testing on `net7.0-ios`).
I will create a Proposal for re-implementing `MemoryAnalysis` that will include the unit tests for `.net7.0-ios`. I will add the `blocked` label to the Proposal until device unit testing is available.

Revert `MemoryAnalyzer` PR Until Device Unit Testing is Available

---

samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml

Updates the sample of the simple popup by including a couple of images and one of them using the Icon Tint Color Behavior.
- Fixes [#663](https://github.com/CommunityToolkit/Maui/issues/663)
- [] Has tests (if omitted, state reason in description)
@brminnick please find on this PR the popup sample updated with the icon tint color samples.

Sample icon tint color behavior inside a popup

---

src/CommunityToolkit.Maui.Core/Views/RoundedView.macios.cs

This PR resolves the issue where when a long message that does not include a line feed code is specified for Snackbar and Toast, it is not drawn correctly after the screen is rotated.
Override the LayoutSubviews method of the RoundedView class that draws the Snackbar and Toast background and call the Draw method so that the Snackbar and Toast are redrawn after the screen is rotated.
[src\CommunityToolkit.Maui.Core\Views\RoundedView.macios.cs]
/// <inheritdoc />
public override void LayoutSubviews()
{
base.LayoutSubviews();
Draw(Frame);
}
This will cause Snackbar and Toast to be redrawn after the screen is rotated, so they will be drawn at the intended size.
This also resolves the issue where the corner shapes of Snackbar and Toast appear to have changed without being redrawn.
- Fixes …

Add redrawing of Snackbar and Toast when the screen is rotated

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs

This PR solves an issue with where a MacCatalyst application has multi-windows enabled, but when creating a popup, it opens up to a random window instead of the correct one.
There is an issue with this line of code:
`var rootViewController = WindowStateManager.Default.GetCurrentUIViewController() ?? throw new InvalidOperationException($"{nameof(PageHandler.ViewController)} cannot be null.");`
It assumes that the application will be in a single-window state (e.g. Shell app). However, with MacOS, apps [can also be multi-window applications](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/windows#multi-window-support).
This fix looks through all windows, locates its "View" (e.g. ContentPage), then compares it against the Parent View of the Popup. If it matches, then that is where …

[MacCatalyst] Get correct window associated with the Popup

---

src/CommunityToolkit.Maui.Core/Handlers/Popup/PopUpHandler.windows.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs

This PR null the `Popup.Parent`  to prevent memory leaks, it will mostly occur when the parent is a `MainPage` (root page) or `Shell`.
Probably, you may think "Wait, but .NET MAUI doesn't handle that internally?", yeah it does but for `VisualElement` , ` Popup` is an `Element` and doesn't get all this love, so we need to do that by ourselves. :/
- Fixes #721
Before:
You see the CustomPopup holding on memory.
After:
No more references to it, YaY:

Fix Memory leak on Popup

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/SelectAllTextBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Resources/Styles/Colors.xaml

Updated the StaticResource set for the border, since it was preventing to navigate to the **SelectAllText** page on macOS only. It works on iOS, Android, and Windows as well.
The documentation has been created on the following PR: https://github.com/MicrosoftDocs/CommunityToolkit/pull/316
- Fixes [#432](https://github.com/CommunityToolkit/Maui/issues/432) 
cc: @pictos @brminnick

Fix for the navigation to the SelectAllText page on macOS

---

src/CommunityToolkit.Maui/Views/Expander/Expander.shared.cs

This PR resolves the issue where the Expander tap does not work when the Expander is placed outside the display range of the ScrollView.
Fixed to call InvalidateMeasure method if element.Parent is ScrollView.
[src\CommunityToolkit.Maui\Views\Expander\Expander.shared.cs]
void ResizeExpanderInItemsView(TappedEventArgs tappedEventArgs)
{
if (Header is null)
{
return;
}
Element element = this;
var size = IsExpanded
? Measure(double.PositiveInfinity, double.PositiveInfinity, MeasureFlags.IncludeMargins).Request
: Header.Measure(double.PositiveInfinity, double.PositiveInfinity);
while (element is not null)
{
if (element.Parent is ListView && element is Cell cell)
{
#if IOS || MACCATALYST
throw new NotSupportedException($"{nameof(Expander)} is not yet supported in {nameof(ListView)}");
#else …

Add forced update of ScrollView on iOS

---

src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs
src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs
src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs

This PR will correct the following:
1. Correct so that VerticalTextAlignment and HorizontalTextAlignment function correctly when a label is placed in the Popup's content.
2. When Popup Size is not specified and WidthRequest and HeightRequest of Popup Content are specified, change the Popup so that it is displayed at the intended size.
Below is the first change.
[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.android.cs]
static void Measure(AView view, int width, int height, bool isNanWidth, bool isNanHeight, ref bool isRootView)
{
if (isRootView)
{
isRootView = false;
view.Measure(
MeasureSpec.MakeMeasureSpec(width, !isNanWidth ? MeasureSpecMode.Exactly : MeasureSpecMode.AtMost),
MeasureSpec.MakeMeasureSpec(height, !isNanHeight ? MeasureSpecMode.Exactly : …

Addition of size calculation for Label placed in Popup and correction of size calculation when Popup Size is not specified

---

src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs

This PR resolves the issue where Popup is not displayed near the anchor when specifying Popup anchor.
When I corrected the [popup's display position and size](https://github.com/CommunityToolkit/Maui/commit/22b158aa77b3763e5ef145fd7a1ca2d034176e21), I did not give top priority to the conditional branch when Anchor was specified, so the conditional branch when VerticalOptions and HorizontalOptions were specified took priority. This is my mistake, sorry.
I modified the conditional branch as follows.
[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.windows.cs]
public static void SetLayout(this Popup mauiPopup, IPopup popup, IMauiContext? mauiContext)
{
ArgumentNullException.ThrowIfNull(mauiContext);
ArgumentNullException.ThrowIfNull(popup.Content);
var popupParent = …

Fix a bug when specifying an Popup's Anchor on Windows

---

src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.shared.cs

In .NET 8, .NET MAUI added a new method to `Element` using the same method signature, `RemapForControls()`.
Since `Popup` inherits from `Element`, `Popup.RemapForControls()` is now unintentionally hiding `Element.RemapForControls()`.
https://github.com/dotnet/maui/blob/8e933a7a7a46fdb586918e7414345d978cb0878d/src/Controls/src/Core/Element/Element.Mapper.cs#L9-L22
```cs
public partial class Element
{
/// <summary>
/// Maps UI information to platform-specific implementations for accessibility services
/// </summary>
[Obsolete("Use ViewHandler.ViewMapper instead.")]
public static IPropertyMapper<Maui.IElement, IElementHandler> ControlsElementMapper = new ControlsMapper<IElement, IElementHandler>(ViewHandler.ViewMapper);
internal static void RemapForControls()
{ …
```

Fix `Popup.RemapForControls()`

---

src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs

This change should prevent "ambiguous reference" error to occur when other packages are included in a MAUI project that provide their own Color objects.
Examples of such libraries is MudBlazor.
In the source code generator use a fully qualified namespace to the Color object, so Color is changed into global::Microsoft.Maui.Graphics.Colors following the example for the similar solution for of #1331 
As per previous PR, no tests added, current tests are sufficient to cover this change (and using the wrong value fail).
- Fixes #1535

Use fully qualified namespace for Colors reference in TextToColorGenerator

---

src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj

This PR removes the `SkiaSharp.Views` dependency for Tizen which has been added to remove the security vulnerability caused by `Tizen.UIExtensions` package.
- Fixes https://github.com/CommunityToolkit/Maui/issues/1424

Remove SkiaSharp.Views Dependency

---

src/CommunityToolkit.Maui.UnitTests/Views/AvatarView/AvatarViewImageTests.cs
src/CommunityToolkit.Maui/Views/AvatarView.shared.cs

- Bug fix
https://github.com/CommunityToolkit/Maui/issues/509
This bug occurs if we use any instance of class derived from ``` GeometryGroup ```  as default clip for image in AvatarView on MacOs or IOS. In AvatarView ``` RoundRectangleGeometry ``` was used as default clip for image. This caused background color to overlay image.
In this pull request I decided not to set clip object if AvatarView is used on IOS/MacOS with this approach background does not overlay image on IOS or MacOS and  ``` RoundRectangleGeometry ``` still be used as default image clip for other platforms.
How it looks in MacOS 
In IOS

Fix IOS/MacOS AvataView background color with image bug

---

src/CommunityToolkit.Maui.Core/Layouts/UniformItemsLayoutManager.shared.cs
src/CommunityToolkit.Maui.UnitTests/Layouts/UniformItemsLayoutTests.cs

[BUG] [Windows] UniformItemsLayout item positioning not correct #1553

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

- Bug fix for HLS CTD on Windows
Reset position and duration when switching sources
Issue: [https://github.com/CommunityToolkit/Maui/issues/1538](https://github.com/CommunityToolkit/Maui/issues/1538)
- Fixes #1538
This issue is not directly an issue with media element as it is the slider that crashes. This PR fixes that issue. I checked android to see if the position and duration is reset when changing sources. It is not. It reset either on opening or when media fails. Do we want to go back and change this in the future? If we do we should check every device for this issue. Or is this intended behavior and only an issue in windows due to slider behavior on that platform?
This might give some insight into slider behavior and a current issue being tracked with it. …

Fix HLS CTD on Windows

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/IconTintColorBehaviorViewModel.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs

Removes the transparent color that was being set on Android when the icon tint color value is set to null.
- Fixes [#1579](https://github.com/CommunityToolkit/Maui/issues/1579)
- [ x] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
- [ x] Rebased on top of `main` at time of PR
- [ x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)

Removes the transparent color set on Android when null

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/IconTintColorBehaviorViewModel.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.ios.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.macos.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.macios.cs
src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
src/CommunityToolkit.Maui/Behaviors/AnimationBehavior.shared.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs

This PR replaces `Microsoft.Extensions.Http.Polly` with `Microsoft.Extensions.Http.Resilience`.
In .NET 8, Microsoft teamed up with the `App-vNext.Polly` team to create a more-performant version of `Polly`.  The new `Microsoft.Extensions.Http.Resilience` library uses the new, more performant version of `Polly`.
Meanwhile `[Microsoft.Extensions.Http.Polly](https://www.nuget.org/packages/Microsoft.Extensions.Http.Polly)` uses the older, less performant, version of `Polly` now rebranded as `Polly.Core.`
To ensure our Sample App adheres to best practices recommended for all .NET MAUI developers, we are upgrading `Microsoft.Extensions.Http.Polly` with `Microsoft.Extensions.Http.Resilience`.
More information is available in this .NET Blog Post: …

[Sample App] Add Microsoft.Extensions.Http.Resilience

---

src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs

Android File Saver - remove MemoryStream

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/AvatarView/AvatarViewImagesPage.xaml

As discussed on the last .NET Community Toolkit Stand Up. This PR updates the Avatar sample to include badge views from label, images, and paths. They are set on different position as well just for demo purposes.
- #105
Please find below screenshots of the badge on Windows, Android and iOS:

Avatar sample updated to include badges

---

Directory.Build.props
azure-pipelines.yml
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj

Match versions of `Microsoft.Maui.Controls` and `Microsoft.Maui.Controls.Compatibility`
Fixes https://github.com/CommunityToolkit/Maui/issues/1693

🔥 FIX - fix unit tests

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.macios.cs

We subscribe to OnElementPropertyChanged only once - OnAttached - instead of each time the TintColor is changed
Every time when color was applied, the void was added to event handler. It causes that every next ImageSource change, invoked heavy color logic multiple times
Move dispose and subscibe logic right place in ImageTintBehavior
- Fixes #1612

Memory leak on TintedImageBehavior fix

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml
samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Sample/Pages/PlatformSpecific/NavigationBarPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/PlatformSpecific/NavigationBarPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/Pages/PlatformSpecific/PlatformSpecificGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/PlatformSpecific/NavigationBarAndroidViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/PlatformSpecific/PlatformSpecificGalleryViewModel.cs
src/CommunityToolkit.Maui.Core/Extensions/AndroidSystemExtensions.android.cs
src/CommunityToolkit.Maui.Core/Extensions/WindowExtensions.android.cs
src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.android.cs
src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs
src/CommunityToolkit.Maui/PlatformConfiguration/AndroidSpecific/Models/NavigationBarStyle.cs
src/CommunityToolkit.Maui/PlatformConfiguration/AndroidSpecific/NavigationBar.Impl.android.cs
src/CommunityToolkit.Maui/PlatformConfiguration/AndroidSpecific/NavigationBar.Properties.cs

This PR implements our first platform-specific feature. It's a move on from the approach taken on #1665. 
Documentation will be created after the PR review.
- Fixes #103
https://github.com/CommunityToolkit/Maui/assets/20712372/5baccce2-14d2-4f92-b021-0e948121ba19

[First - PlatformSpecific] NavigationBar for Android 

---

Directory.Build.props
azure-pipelines.yml

This PR increases the dependencies for the following NuGet Package to v8.0.7:
-  `Microsoft.Maui.Core`
- `Microsoft.Maui.Controls`
- `Microsoft.Maui.Controls.Compatibility`
- `Microsoft.Maui.Controls.Maps`
- `Microsoft.Maui.Essentials`

Increase `Microsoft.Maui.*` Dependencies to v8.0.7

---

src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupTests.cs
src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs
src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.windows.cs

Call `AddLogicalChild`/`RemoveLogicalChild` when the popup is shown/closed so that popups are included in the logical (and visual) tree, so that Hot Reload works for them. The Live Visual Tree VS UI now shows popup content as well.
As Shane explained to me, the rule as of MAUI in .NET8 is that whenever `Parent` is set on an `Element` currently, `AddLogicalChild` should be called on the new parent instead. `AddLogicalChild` takes care of both updating the children and parent, whereas updating the `Parent` only updates the parent not children (and will likely be deprecated). Likewise, `RemoveLogicalChild` should be called when the Parent is set to null currently.
Fixes #620

Fix Hot Reload with Popup

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/StatusBarBehaviorPage.xaml.cs

This might not be completely necessary as it doesn't currently conflicting with our samples page but... the code removed here does conflict if a developer opts for just providing a value into the `StatusBarBehavior` (e.g. 
```xaml
<Page.Behaviors>
<mct:StatusBarBehavior
StatusBarColor="Red"
StatusBarStyle="{Binding Source={x:Reference Page}, Path=BindingContext.StatusBarStyle}" />
</Page.Behaviors>
```
The resulting behaviour will be that no Color will exist and the status bar (at least on iOS) will be Black.

Remove the old code to set the status bar behavior values

---

src/CommunityToolkit.Maui.MediaElement/MediaElement.shared.cs

Fixed Memory Leak in MediaElement.  
The timer is now disposed as well.
- Fixes #1702
Tested on: `WinUI`, `Android`, `iOS`
My Issues hasn't been approved yet, but I thought I nevertheless share my findings with this PR.
I hope you can merge it, in order to improve memory management for people using the `MediaElement`.
P.S.:
As mentioned in the Issue, besides disposing the handler, I had to dispose the `MediaElement` itself as well to get rid of the Memory Leak:
```cs
MyMediaElement.Handler?.DisconnectHandler();
MyMediaElement.Dispose();
````
But I think this can be added to the docu+sample later on...
Many thanks!

Fixes #1702: Fixed Memory Leak in MediaElement

---

src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs

1. In the `MauiMediaElement` constructor, we added setting of the `Visibility`. Now, the `Visibility` property is set to `Collapsed` in the constructor.
2. A new conditional statement has been added to the `OnMediaPlayerElementPointerMoved` method. If the `Visibility` property of `mediaPlayerElement.TransportControls` is `Collapsed`, the `Visibility` property of `buttonContainer` is also set to `Collapsed` and the method returns early. This behavior was not present in the previous version of the method.
https://github.com/CommunityToolkit/Maui/assets/4167863/cd2226fa-2d1e-4c7e-8e24-db59f039698f
https://github.com/CommunityToolkit/Maui/assets/4167863/296a27ec-3e9b-4078-bfcc-f95b03c39118
- Fixes #1745
This applies to a windows specific issue with a button that did not comply with the …

Fix Media Element Transport controls visibility

---

src/CommunityToolkit.Maui.Maps/AppHostBuilderExtensions.shared.cs

As part of enabling the .NET MAUI Maps for Windows we call `UseMauiMaps` in the .NET MAUI SDK.
While this worked before, it was unnecessary to do so. Due to a recent change in .NET MAUI, which now throws a exception with a clear error message, this now became problematic. Because of this change in .NET MAUI, now an exception is always thrown, also through our library when you're actually trying to enable Windows.
This change removes the call to .NET MAUI Maps `UseMauiMaps`, users will have to call this themselves, which would then look something like:
```csharp
var builder = MauiApp.CreateBuilder();
builder
.UseMauiApp<App>()
.ConfigureFonts(fonts =>
{
fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
});
#if IOS || …
```

Not use UseMauiMaps

---

azure-pipelines.yml

The Maps package was not included in the step to set the right version number for the PR artifacts

Also update Maps NuGet version number for PR builds

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Sample/Pages/Alerts/AlertsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Converters/ConvertersGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Essentials/EssentialsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Extensions/ExtensionsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/ImageSources/ImageSourcesGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Layouts/LayoutsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupSizingIssuesPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupSizingIssuesPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/ViewsGalleryPage.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Alerts/AlertsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/BehaviorsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/EssentialsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Extensions/ExtensionsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/ImageSources/ImageSourcesGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/LayoutsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/PlatformSpecific/PlatformSpecificGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/PopupSizingIssuesViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs

This PR doesn't aim to fix anything, its purpose is to provide a more comprehensive set of `Popup` based samples to make verification of change/fixes easier.
The current approach relies on a bit of magic:
```csharp
void OnShowPopup(Page page)
{
var popup = new Popup();
if (SelectedContainer?.ControlTemplate.LoadTemplate() is not View container)
{
return;
}
container.GetType().GetProperty(nameof(IPaddingElement.Padding))?.SetValue(container, new Thickness(Padding));
const string longText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum …
```

Add popup sizing page to cover more test scenarios

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs

- Bug fix
The most significant changes involve the removal of the `MediaElementUnloaded` method and the `Unloaded` event handler from the `MediaElementPage.xaml.cs` and `MediaElementPage.xaml` files respectively. These were previously used to disconnect the handler when the media element was unloaded. Additionally, the `OnNavigatedFrom` method in the `MediaElementPage.xaml.cs` file was updated to stop the media element from playing when navigation away from the page occurs.
List of changes:
1. Removal of the `MediaElementUnloaded` method from the `MediaElementPage.xaml.cs` file. This method was previously used to disconnect the handler when the media element was unloaded.
2. Update to the `OnNavigatedFrom` method in the `MediaElementPage.xaml.cs` file to include a call to …

Fix IOS crash when entering Full Screen

---

samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.shared.cs
src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs
src/CommunityToolkit.Maui/Options.cs

Snackbar now requires additional code to be added on Windows to the Package.appxmanifest file: https://github.com/MicrosoftDocs/CommunityToolkit/pull/374
Currently, without adding this additional code to `Package.appxmanifest`, `CommunityToolkit.Maui` causes all Windows apps to crash on launch. 
This PR adds `Options.ShouldEnableSnackbarOnWidows` to allow users to opt-in to enabling Snackbar on Windows, ensuring that they have added the additional required code to `Package.appxmanifest`.
```cs
var builder = MauiApp.CreateBuilder()
.UseMauiCommunityToolkit(options =>
{
options.SetShouldEnableSnackbarOnWindows(true);
})
```

Add Platform-Specific Option to Enable Snackbar on Windows

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/TouchBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/TouchBehaviorPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/TouchBehaviorViewModel.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.shared.cs

Update the `TouchBehavior` sample gallery to show the recommended method of setting of setting the binding context for the `TouchBehavior`.
I have included a new usage with the `CommandParameter` to help clearup some confusion we've been seeing for people consuming this `Behavior` upon release.
N/A
[Docs PR](https://github.com/MicrosoftDocs/CommunityToolkit/pull/399)
I've run `dotnet format` and checked that in, some minor changes all in the `TouchBehavior` area.
Screenshots of changes to the sample:

Update Touch Behavior Sample

---

src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.targets
src/CommunityToolkit.Maui.MediaElement/Resources/Images/fullscreen.svg
src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.windows.cs

https://github.com/CommunityToolkit/Maui/assets/4167863/1f481dc4-5f6e-40d3-aefe-3595cfce58a1
The most significant changes to the `MauiMediaElement` involve modernizing the fullscreen controls by transitioning from using static SVG images to adopting `FontIcon` elements for better flexibility and visual consistency. This shift enhances the user interface and interaction model for entering and exiting fullscreen mode. The key changes include:
1. **Removal of fullscreen.svg Resource**: The static `fullscreen.svg` image resource was removed, indicating a move away from static images for the fullscreen button.
2. **Introduction of Font Icons for Fullscreen Controls**: Replacing the `Image` with `FontIcon` elements for fullscreen controls, utilizing glyphs from the "Segoe MDL2 Assets" font for …

Bug fix for MediaElement File Duplication

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs

Event handler was not disposed. That led to crash System.DisposedObject
#1819
#1710
- Fixes #
Android only

Fixing crash in IconTintColorBehavior

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs

- Bug fix
The primary change made to the code involves enhancing the validation of the `path` variable. Previously, the code checked if the `path` was neither null nor consisted solely of whitespace. The update extends this validation by also verifying that the `path` includes an extension. This adjustment is crucial for ensuring that operations such as retrieving the directory name, the filename without its extension, and the file extension itself are only executed on valid file paths. This modification aims to mitigate potential errors or unexpected outcomes when the code encounters paths that do not correspond to actual files, which would characteristically include extensions.
- Enhanced validation of the `path` variable to include a check for the presence of a file extension, in …

Fix IOS crash on invalid or missing file extension on Resource Media Source

---

src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs

This PR resolves the following issue that occurs when displaying Popup on iPhone 11 or lower, iPhone Plus, and iPhone Pro Max.
1. An issue that caused a crash when displaying a Popup when the device was in landscape orientation.
2. An issue where rotating the device while viewing a popup would cause a crash.
The exception is occurring at the location below, but it is not caused by the SetShadowView method.
[src\CommunityToolkit.Maui.Core\Views\Popup\MauiPopup.macios.cs]
static void SetShadowView(in UIView target)
{
if (target.Class.Name is "_UICutoutShadowView")
{
target.RemoveFromSuperview();
}
if (target.Class.Name is "_UIPopoverDimmingView")
{
target.BackgroundColor = UIColor.Black.ColorWithAlpha(0.4f);
}
foreach (var view in target.Subviews)
{
SetShadowView(view);
}
}
Below is the …

Add PresentationStyle

---

src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.android.cs

- Bug fix
The primary changes to the `MauiMediaElement` class involve a significant refactoring to enhance layout management and simplify the handling of fullscreen mode for the media player. The key modifications include transitioning to a `RelativeLayout` for better flexibility in positioning the `StyledPlayerView`, removing explicit player size management in favor of relying on layout parameters, and streamlining the process for entering and exiting fullscreen mode. These adjustments lead to a more readable and maintainable codebase, with improved centering and sizing of the player view.
1. **Refactoring to Use RelativeLayout**: Transitioned the layout management of the `StyledPlayerView` from a `CoordinatorLayout` to a `RelativeLayout` for improved flexibility in positioning and …

Fix MediaElement Layout for Android

---

src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs

This PR aims at working around an issue on Android when the `Text` property is updated programmatically during the `TextChanged` event then the `CurrentPosition` property is overridden once completed.
- Fixes #1913
- Fixes #460

Queue up the Text update when running on Android

---

src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs

Applies review comments from #1922

Tidy up the masked text behavior handling of text changed

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsListNullOrEmptyConverterPage.xaml
src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs

This PR is the result of some great investigative work by @GalaxiaGuy. It seems that an exception would be handled within the `ValidateTargetType` method. This PR reorders the checks to avoid this exception.
- Fixes #1689

Swap the order of checks to prevent an unnecessary exception

---

azure-pipelines.yml

In the build pipeline we were missing a bit where `CommunityToolkit.Maui` and `CommunityToolkit.Maui.Core` were excluded when we do a tagged build for `CommunityToolkit.Maui.Camera`.
Adds a condition to our build pipeline to NOT copy `CommunityToolkit.Maui` & `CommunityToolkit.Maui.Core` NuGet packages to staging directory when building `CommunityToolkit.Maui.Camera`.
N/A

Don't copy Core & main package to artifacts for Camera package build

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsListNullOrEmptyConverterPage.xaml
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs
src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs

Added check for if the bindable object has a UriImageSource and added it as a UriSource for the WImage control. Previously, the WImage control source was null.
- Fixes #1906
Tested on Windows 10
This is an update to a previous PR #1929 which introduced a new issue, but this PR only addresses one of the issues linked in the old PR.

Fix IconTintColorBehavior not tinting UriImageSource on Windows

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.macios.cs
src/CommunityToolkit.Maui.MediaElement/Primitives/Metadata.windows.cs
src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs

- Bug fix
Add static keyword to a few methods
Replace deprecated IOS API's
Deprecated API's
- `MPMediaItemArtwork`
- `Player.PreventsDisplaySleepDuringVideoPlayback`
- Fixes #1954
As brought up earlier there are a few issues with existing code that need to be fixed. Code compliance with dotnet standards and repository best practices.

Update Media Element to fix code compliance

---

src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs

Currently the volume bar keeps popping up on Android whenever you interact with `MediaElement`, this change will stop that as it look a bit funny to me.
N/A, just a Gerald annoyance 😜

Prevent volume bar from popping up on Android

---

src/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes/CodeFixResources.Designer.cs
src/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes/CodeFixResources.resx
src/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes/UseCommunityToolkitCameraViewInitializationAnalyzerCodeFixProvider.cs
src/CommunityToolkit.Maui.Camera.Analyzers/Resources.Designer.cs
src/CommunityToolkit.Maui.Camera.Analyzers/Resources.resx
src/CommunityToolkit.Maui.Camera.Analyzers/UseCommunityToolkitCameraInitializationAnalyzer.cs

I think one namespace was forgotten in the rename from CameraView to Camera and that is probably why the analyzer couldn't locate things.
- Fixes #1991

Fix Camera analyzer

---

azure-pipelines.yml

This PR updates our CI pipeline to use the latest version of macOS, Sonoma, and the latest supported version of Xcode, v15.3.0.

[Housekeeping] Update CI Pipeline to use macOS Sonoma and Xcode 15.3.0

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/CompareConverterPage.xaml

Changed the value of the `Comparingvalue` to be 50% of the `Slider` range, thus matching the label text.  Not unit tests or documentation need to be updated.
- Fixes #1980
Tested on:

Information label and bound value in CompareConverter sample don't match

---

samples/CommunityToolkit.Maui.Sample/Platforms/Android/AndroidManifest.xml
src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs

- Changed the service name in AndroidManifest.xml and MediaControlsService.android.cs from `CommunityToolkit.Maui.Media.Services` to `communityToolkit.maui.media.services` to adhere to lowercase naming conventions.
- Fixes #2043
Service name changed to prevent crash on API level below 24. It has had all uppercase letters replaced with lowercase to maintain compliance with earlier standards.

[BUG FIX] Fix Android APK crash on API Level 21-24

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/IconTintColorBehaviorPage.xaml.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.windows.cs

Updated IconTintColorBehavior Android and Windows implementations so they apply the tint to Button images like on iOS and Mac Catalyst.
- Fixes #2040
PR submitted as draft due to issue [#2040](https://github.com/CommunityToolkit/Maui/issues/2040) awaiting approved. AFAICT updates to existing documentation, tests, and samples are not required.

Update IconTintColorBehavior so it applies tint to Button image on Android and Windows like iOS and Mac Catalyst

---

samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj

- Bug fix
Revert removal of `<UseMaui>true<</UseMaui>` in sample csproj
- Fixes #2056
Fixes cannot build and/or run on any device/emulator.

[Sample App] Add `<UseMaui>true</UseMaui>`

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/MultiConverterPage.xaml
src/CommunityToolkit.Maui.UnitTests/Converters/VariableMultiValueConverterTests.cs
src/CommunityToolkit.Maui/Converters/VariableMultiValueConverter.shared.cs
src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs

This fix updates the logic for `IsValidTargetType(Type, bool)` to use the `targetType` parameter passed into the method when verifying the nullable value types.
- Fixes #2003 
I _think_ this is the fix. But I'll defer to @bijington as the expert here since he added the nullable value type check in this PR: https://github.com/CommunityToolkit/Maui/pull/1926
The exception being thrown in https://github.com/CommunityToolkit/Maui/issues/2003 was caused by using MultiBindings where `TTo` may not match `Type targetType`.

Fix Target Type Validation

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs

Following #1883, which fixed an ObjectDisposedException crash in `ApplyTintColor`, this PR fixes a crash in `ClearTintColor` in the same manner. Other users have reported experiencing this in the replies to the original issue linked below.
- Fixes #1819 
Android only. Reproduced reliably in a production application on an Android 11 device, cannot reproduce after patch is applied.

fix: Fix unhandled ObjectDisposedException in IconTintColorBehavior.ClearTintColor on Android

---

azure-pipelines.yml

CI pipelines are currently broken with:
```
ILLINK : warning MT0079: The recommended Xcode version for Microsoft.MacCatalyst 17.5.8018 is Xcode 15.4 or later. The current Xcode version (found in /Applications/Xcode_15.2.0.app/Contents/Developer) is 15.2. [/Users/runner/work/1/s/samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj::TargetFramework=net8.0-maccatalyst]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/runner/work/1/s/samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 17.5 SDK (shipped with Xcode 15.4). Either upgrade Xcode to get the …
```

Update to Xcode 15.4 in CI pipelines

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs

Related to the last PR for this issue (#2012). This PR explicitly catches ObjectDisposedException in the same way as [TouchBehavior](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.android.cs#L105). Not an optimal solution, but it's a simple fix and makes absolutely sure that it won't crash the app.
- Fixes #1819 
Android only, occurs in a production application. After the previous PR the crash couldn't be reproduced, but a few occurrences were spotted in error reporting.

Catch ObjectDisposedException in IconTintColorBehavior

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs

- Bug fix
Add poster support for artwork in Android when using MediaElement. When you play music it will now show a default poster from metadata artwork Url if present.
- Fixes #2107
https://github.com/user-attachments/assets/d3dad3d2-bd06-4dcd-a64c-45c49fe56748

Enhance media player with artwork display support

---

samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/StatusBarBehaviorPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/StatusBarBehaviorViewModel.cs
src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.ios.cs

While working on a Blazor Hybrid project I implemented the StatusBarBehavior. I also added the new way of setting the root page for a .NET MAUI app by not using MainPage (also see #2054)
I ran into an issue that when setting the status bar color from XAML, I would get an exception. Probably due to the fact that the window isn't created yet, but the page is being created that wants to set the status bar.
To be ahead of the curve for this new change in .NET MAUI, I adapted this code a little so that it doesn't thrown an exception but handles it more gracefully. The actual functionality still seems to work fine.

Make iOS StatusBarBehavior more robust and not throw exceptions

---

src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Views/MediaElement/ParentWindowTests.cs

- Bug fix
Fix failing test on Azure pipelines. it fails about 8 percent of the time. It has zero percent failure on my local machines. Passes on Mac mini and two different windows PC's. I have no idea why it only fails a small percentage of the time and only on Azure pipelines.

Fix failing test on Pipelines. Test only fails on Pipelines.

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.android.cs

Take look into `OnDetachedFrom()`
```CSharp
protected override void OnDetachedFrom(VisualElement bindable, AView platformView)
{
base.OnDetachedFrom(bindable, platformView);
view = platformView;
if (Element is null)
{
return;
}
...
```
We exiting when `Element` is null.
The thing is that  `Element`  is always null because it returns a `View`  and `base.OnDetachedFrom()` calls `UnassignViewAndBingingContext()` which sets it to null. 
- Fixes #2082
- [x ] Has a linked Issue, and the Issue has been `approved`(bug) or `Championed` (feature/proposal)
- [x ] Rebased on top of `main` at time of PR
- [ x] Changes adhere to [coding standard](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#contributing-code---best-practices)
Sample code is not needed. You can check it using a …

Removed spare Element checking in OnDetachedFrom

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
src/CommunityToolkit.Maui.UnitTests/Views/MediaElement/MediaElementTests.cs

- Bug fix
- Updated `UpdateMetadata` in `MediaManager.windows.cs` to return early if `MediaElement.MetadataArtworkUrl` is null or empty.
- Added tests in `MediaElementTests.cs`:
- `PosterIsNotStringEmptyorNull`: Verifies `MetadataArtworkUrl` is not null or empty when set to a valid URL.
- `PosterIsStringEmptyDoesNotThrow`: Ensures no exceptions when `MetadataArtworkUrl` is an empty string and correctly identifies it as empty.
- 
- Fixes
Fixes a nasty bug where App crashes when you do not set artwork for media element. When setting poster we cannot set it to string empty. That is what is crashing windows. Added `string.IsNullOrEmpty` check to `MediaElement.MetadataArtworkUrl` so that we do not set the poster if it is not present.

Fix MediaElement CTD on Windows

---

src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs

- Bug fix
In Android service destroy method the app was exiting. I removed the app exit method calls and now the destroy method only shuts the service down. This is still required as pressing back button to exit page should close service.
- Fixes #2143
I had put a call to exit app in the Destroy method for Android notification service and did not realize the back button would call it. It has been removed now. I tested against the provided sample and the app does not close when pressing back button in Android now. I kept the call to end service when you leave page. 
I need that to be there for lifecycle behavior when app is restored from being killed by OS it is retaining state when it should not. This `Platform.CurrentActivity?.StopService(new Intent(Platform.AppContext, …

Fix Android App Exit On Back button pressed

---

src/CommunityToolkit.Maui.MediaElement/Services/MediaControlsService.android.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs

- Bug fix
Remove confusing log Message in `MediaElement` that led to questions about app behavior.
There was a question asked on StackOverflow about the error message and its possible implications in an app crash from a developer. The log message displayed an error about a class being deprecated as of Android 33. This log message has no impact on behavior and has confused developers about the apps behavior. This PR removes the message as it is not needed and is confusing people

Remove log messages that were confusing and not required.

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

- Bug fix
Add null check for `MediaElement.MetadataArtworkUrl` in `UpdateMetadata` to fix a crash to desktop in Windows. This fixes an issue where the application will crash if the artwork URL is a `string.empty` which is the default if developer does not set the value.
- Fixes #2150

Fix MediaElement CTD in Windows

---

src/CommunityToolkit.Maui.Camera/CameraManager.android.cs

Remove the use of DisableAutoCancel to allow CameraX to automatically cancel focus and metering actions after the default duration, enabling continuous auto-focus behavior rather than being locked into the initial focal point.
- Fixes #2103
See https://github.com/CommunityToolkit/Maui/issues/2103#issuecomment-2312888790 for video example

Remove DisableAutoCancel to fix Android auto focus

---

src/CommunityToolkit.Maui/Behaviors/AnimationBehavior.shared.cs

Fix https://developercommunity.visualstudio.com/t/Hot-reload-stops-working-when-using-Comm/10707756
Control properties should have both a getter and setter so that Hot Reload (and C# code) can update them.
AnimateCommand was missing the setter - likely just an oversight. Hot Reload now works with this change.
- Fixes # https://developercommunity.visualstudio.com/t/Hot-reload-stops-working-when-using-Comm/10707756

Add missing setter for AnimateCommand

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs

- Bug fix
Modified the GetPageRoute method in AppShell.xaml.cs to change the route string format from single slashes to double slashes between galleryPageType.Name and contentPageType.Name. This update aligns with the new routing convention or framework requirement.
- Fixes #2189
This fixes an issue where starting sample app on windows results in app crashing. This is path issue that this PR addresses.

Update GetPageRoute to use double slashes in route format

---

src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj

Make test sdk match the test runner on the Mac build agent

---

src/CommunityToolkit.Maui.Core/Handlers/Popup/PopupHandler.shared.cs
src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs

In this PR, by applying PR #2166, we resolve the issue where Popup is not closed when the Close or CloseAsync method is called.
I added the following code to PR #2166.
[src\CommunityToolkit.Maui\HandlerImplementation\Popup\Popup.shared.cs]
```
public static CommandMapper<IPopup, PopupHandler> ControlPopUpCommandMapper = new(PopupHandler.PopUpCommandMapper)
{
#if IOS || MACCATALYST
[nameof(IPopup.OnOpened)] = MapOnOpened,
[nameof(IPopup.OnClosed)] = MapOnClosed          // <= here
#endif
};
```
The above code will no longer call the following method.
[src\CommunityToolkit.Maui.Core\Handlers\Popup\PopupHandler.macios.cs]
```
public static async void MapOnClosed(PopupHandler handler, IPopup view, object? result)
{
var presentationController = handler.PlatformView.PresentationController;
if …
```

Changed to call Popup's MapOnClosed method

---

azure-pipelines.yml
samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
samples/CommunityToolkit.Maui.Sample/Pages/Converters/StringToListConverterPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ItemTappedEventArgsConverterViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ListToStringConverterViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/SelectedItemEventArgsConverterViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/ImageSources/GravatarImageSourceViewModel.cs
src/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes/UseCommunityToolkitCameraViewInitializationAnalyzerCodeFixProvider.cs
src/CommunityToolkit.Maui.Camera.Analyzers/UseCommunityToolkitCameraInitializationAnalyzer.cs
src/CommunityToolkit.Maui.Core/Views/DrawingView/DrawingLine.shared.cs
src/CommunityToolkit.Maui.MediaElement/Primitives/AndroidMediaPermissions.android.cs
src/CommunityToolkit.Maui.UnitTests/BaseHandlerTest.cs
src/CommunityToolkit.Maui.UnitTests/Behaviors/MaskedBehaviorTests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/StringToListConverterTests.cs
src/CommunityToolkit.Maui.UnitTests/Mocks/MockCameraProvider.cs
src/CommunityToolkit.Maui.UnitTests/Mocks/MockDrawingViewHandler.cs
src/CommunityToolkit.Maui.UnitTests/Views/DrawingView/DrawingLineTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/DrawingView/DrawingViewTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/SemanticOrderView/SemanticOrderViewTests.cs
src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MathExpressionConverter.shared.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs

This PR _hopefully_ fixes the [random crashing of the Unit Test host process in our CI/CD pipeline](https://dev.azure.com/dotnet/CommunityToolkit/_build/results?buildId=109660&view=logs&j=3f96dcf5-6e1e-5485-3200-c557d5216be3&t=12286b69-c788-55db-0a8c-ef899858fbe6&l=76):
> The active test run was aborted. Reason: Test host process crashed
The VS Test team has added a new Environment Variable, `VSTEST_TESTHOST_SHUTDOWN_TIMEOUT `, that we can leverage to extend the test runner timeout: https://github.com/microsoft/vstest/blob/02a8ba17b12757e0787b5e787b17533f21432b16/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs#L330.
This PR increases the value of `VSTEST_TESTHOST_SHUTDOWN_TIMEOUT` from its default of 100ms to 11000ms to exceed our [longest defined timeout, …

[Housekeeping] Fix `The active test run was aborted. Reason: Test host process crashed`

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

- Make method `AreFloatingPointNumbersEqual` public and static.
- Update floating point comparisons to use the above `bool` method to determine comparisons. This fixes a small code issue that will possibly prevent issues with event handling.
This fixes some minor code quality issues in Windows. This fixes potential issues with event handling.

Code fixes

---

src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs

- Remove redundant null checks
- Refactory foreach loop to use range operator
- deconstruct variable to return a tuple appropriately
- Add static keyword to tuple `GetVideoDimensions(AVPlayerItem avPlayerItem)`
Minor code quality updates to fix code compliance issues. This PR fixes a redundant null check, deconstructs a variable that returns a tuple and adds the `static` keyword to the same tuple.

MediaElement MacIOS code quality fixes

---

README.md
samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/LazyView/CustomLazyView.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/LazyView/MyViewLazyView.cs
samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/TouchBehavior/TouchBehaviorCollectionViewMultipleSelectionViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ByteArrayToImageSourceConverterViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FileSaverViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/MediaElementCarouselViewViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/MediaElementCollectionViewViewModel.cs
src/CommunityToolkit.Maui/Behaviors/AnimationBehavior.shared.cs
src/CommunityToolkit.Maui/Behaviors/ICommunityToolkitBehavior.shared.cs
src/CommunityToolkit.Maui/Behaviors/ImpliedOrderGridBehavior.shared.cs
src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.methods.shared.cs
src/CommunityToolkit.Maui/Behaviors/Validators/MultiValidationBehavior.shared.cs
src/CommunityToolkit.Maui/Behaviors/Validators/ValidationBehavior.shared.cs
src/CommunityToolkit.Maui/Converters/BaseConverter.shared.cs

- Bug fix
Minor code fixes for sample app. 
- Use string interpolation for URLs in various methods.
- Add default values for `CancellationToken` in `LoadViewAsync`.
- Update logging placeholders for consistent casing in `MediaElementPage.xaml.cs`.
- Switch to `Trace.TraceInformation` in `OnRowTapped`.
- Enhance exception logging in `DownloadDotNetBotImage`.
- Improve code readability and maintainability.

Refactor URLs and improve logging consistency

---

src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MauiMediaElement.macios.cs
src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs

Current behavior of autoplay has player pause on opening. Changing the comparision to `IsZero<double>(MediaElement.Speed)` and `IsZero<double>(previousSpeed)` fixes it.
- Fixes #2237
Recently added comparison for doubles was incorrectly returning bad value when comparing to a value of zero. Issue is fixed by casting int onto the double instead of comparing small variation in value.

Fix Windows Autoplay bug

---

global.json
samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
samples/CommunityToolkit.Maui.Sample/Pages/Essentials/OfflineSpeechToTextPage.xaml
samples/CommunityToolkit.Maui.Sample/Pages/Essentials/OfflineSpeechToTextPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/EssentialsGalleryViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/OfflineSpeechToTextViewModel.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/ISpeechToText.shared.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSharedSpeechToTextImplementation.macios.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToText.shared.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.android.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.ios.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.macos.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.net.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.shared.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.tizen.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.macos.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextOptions.cs
src/CommunityToolkit.Maui.UnitTests/Mocks/SpeechToTextImplementationMock.cs

Offline Speech Recognition #2089

---

src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.macios.cs

Fixes issues when the image source is changed on a ButtonImage in MacCatalyst where IconTintBehavior would throw a null reference on button.CurrentImage due to a race condition.
#2313
- Fixes #
This checks if the CurrentImage is null before proceeding. MacCatalyst and iOS has been tested, both found to have the bug and are fixed with this patch.

[MacCatalyst] [iOS] Fix IconTintColorBehavior ImageButton Disappearing and Crash On Source Change

---

src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs

The MoveToRegion command of the Map changes the location but does not change the span or zoom of the map in Windows. The map should change its zoom/span to the requested parameters.
This fix modifies the setRegion method to utilize the additional zoom parameters.
Modifed the setRegion to utilize zoom lat/lon parameters.
See https://github.com/CommunityToolkit/Maui/issues/1686#issuecomment-2246287104 for example of fix in action.
- Fixes #1686 
Edition	Windows 11 Pro
Version	24H2
Installed on	‎11/‎4/‎2024
OS build	26100.2033
Experience	Windows Feature Experience Pack 1000.26100.23.0

Fixes [BUG] Map not responding to span (zoom) requests in Windows #1686

---

src/CommunityToolkit.Maui.UnitTests/PopupServiceTests.cs
src/CommunityToolkit.Maui/PopupService.cs

Corrects the regression added in 9.1.1 with the `IDispatcher` dependency.
- Fixes #2332

Fixes PopupService scopes problem

---

azure-pipelines.yml
src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Maps/CommunityToolkit.Maui.Maps.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj

Adds the `-p:Version` property to the pipeline which will apply the right version to the assemblies in the NuGets
- Fixes #2299

Version Toolkit assemblies alike the NuGet package version

---

src/CommunityToolkit.Maui.UnitTests/Converters/IsListNotNullOrEmptyConverterTests.cs
src/CommunityToolkit.Maui.UnitTests/Converters/IsListNullOrEmptyConverterTests.cs
src/CommunityToolkit.Maui/Converters/IsListNullOrEmptyConverter.shared.cs

Added check that enumerator is disposable before calling dispose, allowing support for ArrayEnumerator
- Fixes #2395

Fix bug: Support for arrays in IsListNotNullOrEmptyConverter/IsListNotNullOrEmptyConverter

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs

- Bug fix
Fix MVVM warnings about `ObservableProperties` in `SpeechToTextViewModel`. More Can be found here: https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0045
- Fixes #
Fixes `ObservableProperties` by adding `public partial` and adding setters and getters.

Fix mvvmtk0045 warnings for `SpeechToTextViewModel`

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/VariableMultiValueConverterViewModel.cs

- Bug fix
Fix MVVM errors in `VariableMultiValueConverter` View Model. This fixes mvvm0045 errors. This error is caused by not using public partial properties with `ObservableProperties`
- Fixes #
Fixes MVVM errors with `ObservableProperties` and failure to include `public partial`.

Fix mvvmtk0045 warnings for `VariableMultiValueConverterViewModel`

---

samples/CommunityToolkit.Maui.Sample/ViewModels/Layouts/StateContainerViewModel.cs

- Bug fix
Fix mvvmtk0045 errors in View Model for StateContainer.
- Fixes #
Update `StateContainerViewModel` to be compliant with changes to MVVM for dotnet 9 and use public partial for `ObservableProperties`

Fix mvvmtk0045 warning for `StateContainerViewModel`

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/IndexToArrayItemConverterPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/CameraView/CameraViewViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CustomSizeAndPositionPopupViewModel.cs

- Bug fix
Fix XamlC warning XC0045 Value not found
fix MVVM warning mvvmtk0045 
- Fixes #
Fix xamlc compiled binding error with `IndexToArrayItemConverterPage` and MVVM error with `ObservableProperty` not using `public partial`

Fix mvvmtk0045 and XC0045 warnings

---

samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
src/CommunityToolkit.Maui.Core/Essentials/FileFolderDialog.tizen.cs

This PR removes the Null Forgiving Operator (`!.`) in accordance with [our Contribution Guidelines](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#pattern-matching)

[Housekeeping] Remove Null Forgiving Operator

---

azure-pipelines.yml

CI has been failing on the PublishCodeCoverageResults step. Seems like v2 of that step isn't doing great as by reports on the internet. Reverting back to v1 isn't ideal, but seems to be working and is better than disabling this entirely. So doing that for now.

Fix PublishCodeCoverageResults in Azure Pipelines

---

.github/workflows/SignClientFileList.txt
.github/workflows/dotnet-build.yml
azure-pipelines.yml

Initial migration from Azure Pipeline to GitHub Actions.
Skipped NuGet publish.
- Fixes #

Use GitHub Actions

---

src/CommunityToolkit.Maui/Extensions/AppThemeResourceExtension.shared.cs

We forgot to add `IProvideParentValues` as a required service on `AppThemeResourceExtension`. Therefore it would break when used in release mode because it would be trimmed out and not available.
- Fixes #2415

Add IProvideParentValues as required service for AppThemeResourceExtension

---

src/CommunityToolkit.Maui.Camera/CameraManager.android.cs
src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj

Update both `Xamarin.AndroidX.Camera.Camera2` and `Xamarin.AndroidX.Camera.View` packages.  
Fix the call to `SetSurfaceProvider` that changed with the new packages.
- Fixes #2438

[CameraView] Android - Fix SetSurfaceProvider crash

---

src/CommunityToolkit.Maui/Converters/ICommunityToolkitValueConverter.shared.cs

Adds a `UnconditionalSuppressMessage` attribute to `ICommunityToolkitValueConverter.Convert` and `ICommunityToolkitValueConverter.ConvertBack` to fix the IL2092 warnings that are currently emitted when using AOT on iOS.
- Fixes #2447
See https://github.com/CommunityToolkit/Maui/issues/2447#issuecomment-2602449055

Add UnconditionalSuppressMessage to fix IL2092

---

.github/workflows/dotnet-build.yml
src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Mocks/MockPopupHandler.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupTests.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs

This PR fixes the [`ArgumentOutOfRangeException` occurring in  the `Run All Unit Tests` step of our `Build Library (windows-latest)` pipeline](https://github.com/CommunityToolkit/Maui/actions/runs/13037793620/job/36372408491): 
> [xUnit.net 00:00:29.07] Catastrophic failure: System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
The exception was happening because both `MockPopup` and `MockPopupHandler` were both calling `HandlerCompleteTCS.SetResult();` in `OnClosed` causing a race condition where our test would sometimes fail and sometimes pass. 
This PR updates the PopupTests to use `Assert.ThrowsAnyAsync<OperationCanceledException>()` which will pass when either an `OperationCanceledException` is …

[Housekeeping] Fix Unit Test Failure: `Catastrophic failure: System.ArgumentOutOfRangeException`

---

src/CommunityToolkit.Maui.Core/AppBuilderExtensions.shared.cs
src/CommunityToolkit.Maui.Core/Services/DialogFragmentService.android.cs
src/CommunityToolkit.Maui.UnitTests/BaseTest.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/AppBuilderExtensionsTests.cs
src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs

- Bug fix
Currently you cannot opt out of using new functionality for dialogue fragments on android. Setting the option to do so does not work with core. This PR fixes that issue by placing setting options earlier in build order. 
- Fixes #2490
This will allow ppl to opt out of using the new dialogue fragment in recent PR. Atm if you try to navigate to any page in sample app the app crashes to android desktop. This PR will fix that issue by allowing you to opt out. Current the opt out is not working. This PR addresses that issue only. It fixes options so that they work by placing options above core in build order.

Fix options not working for Core

---

Directory.Build.props
samples/CommunityToolkit.Maui.Sample/Pages/Essentials/SpeechToTextPage.xaml
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/DrawingViewViewModel.cs

- Bug fix
Add `x:DataType` to ItemDisplayBinding for `Picker` in SpeechToTextPage.
Fix `ObservableProperty` in DrawingViewModel.
- Fixes #
This fixes two warnings: XamlC warning XC0022, and MVVMTK0045 warning. This may fix some issues that have yet to be reported.

Fix XamlC warning for `DrawingViewModel` and MVVMTK warning `SpeechToTextPage`

---

.github/workflows/dotnet-build.yml
Directory.Build.props
azure-pipelines.yml
global.json
src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj
src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj

This PR bumps `MauiPackageVersion` to `9.0.40` and bumps the minimum .NET SDK version to `9.0.200`.
Thanks to the updated Android Dependencies in the `Microsoft.Maui.Controls` NuGet Package, we can remove the transient Android dependencies in `CommunityToolkit.Maui.Camera` and `CommunityToolkit.Maui.MediaElement`.
The `MauiPackageVersion` property is used to define the version number for every `Microsoft.Maui.*` dependency used in each .NET MAUI Community Toolkit, e.g. `Microsoft.Maui.Controls`, `Microsoft.Maui.Essentials`, etc.
This update requires users to install the latest .NET SDK and the latest MAUI Workloads installed on their local environment. I've added the https://github.com/CommunityToolkit/Maui/labels/requirements%20updated label.
Here is the updated requirements we will need …

Increase `Microsoft.Maui.*` Dependencies to v9.0.40

---

src/CommunityToolkit.Maui.Camera/CameraManager.windows.cs

If you have a depth camera, it might end up using the depth or IR image instead.
- Fixes #2547

Ensure only color streams are used

---

src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.android.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.ios.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.macos.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.net.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.shared.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.tizen.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.android.cs

- Fixes #2541
- Fixes #2463 
https://github.com/user-attachments/assets/f9481eb7-1633-497b-98c4-ff3c438d4c51

SpeechRecognition fixes

---

.github/workflows/dotnet-build.yml
azure-pipelines.yml
global.json

This PR increases our minimum .NET SDK version to v9.0.2.02 to coincide with [increasing our `Microsoft.Maui.*` dependency to v9.0.50](https://github.com/CommunityToolkit/Maui/pull/2584).
Increasing the minimum .NET SDK version ensures that users are required to install the latest .NET MAUI workloads to correspond with the `Microsoft.Maui.*` v9.0.50 libraries.
We will need to include the following in our next release notes:
The following tools are now required for CommunityToolkit.Maui:
- Read the [latest .NET MAUI Release wiki](https://github.com/dotnet/maui/wiki/Release-Versions) to always find the latest-supported version) of Xcode for .NET MAUI 
- We HIGHLY recommend using the open-source tool [Xcodes](https://github.com/XcodesOrg/XcodesApp) to easily manage your installed Xcode …

[Housekeeping] Increase minimum .NET SDK dependency to v9.0.202

---

src/CommunityToolkit.Maui/Behaviors/UserStoppedTypingBehavior.shared.cs

Run UserStoppedTypingBehavior Command on UIThread

---

Directory.Build.props
src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj

- Adding `UseMicrosoftTestingPlatformRunner` in individual projects is discouraged. It's much better to have it in a centralized place like `Directory.Build.props`.
- I don't see a good reason to not set `TestingPlatformDotnetTestSupport` to true as well. So I changed it from false to true.
- Also updated xunit.v3 to 2.0.0

Move UseMicrosoftTestingPlatformRunner to Directory.Build.props

---

.github/workflows/dotnet-build.yml
Directory.Build.props
azure-pipelines.yml
samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
src/CommunityToolkit.Maui.Analyzers.CodeFixes/CommunityToolkit.Maui.Analyzers.CodeFixes.csproj
src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
src/CommunityToolkit.Maui.Analyzers/CommunityToolkit.Maui.Analyzers.csproj
src/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes/CommunityToolkit.Maui.Camera.Analyzers.CodeFixes.csproj
src/CommunityToolkit.Maui.Camera.Analyzers/CommunityToolkit.Maui.Camera.Analyzers.csproj
src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Core/Views/Snackbar/PlatformSnackbar.macios.cs
src/CommunityToolkit.Maui.MediaElement.Analyzers.CodeFixes/CommunityToolkit.Maui.MediaElement.Analyzers.CodeFixes.csproj
src/CommunityToolkit.Maui.MediaElement.Analyzers/CommunityToolkit.Maui.MediaElement.Analyzers.csproj
src/CommunityToolkit.Maui.SourceGenerators.Internal/CommunityToolkit.Maui.SourceGenerators.Internal.csproj
src/CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.csproj
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj

This PR updates the `CommunityToolkitSampleApp_Xcode_Version` in our CI/CD pipelines to use `Xcode v16.3` now that [it is supported in the latest release of .NET MAUI](https://github.com/dotnet/macios/releases/tag/dotnet-9.0.1xx-xcode16.3-9288)

[Housekeeping] Increase Xcode to 16.3 for Sample App Builds in CI/CD Pipelines

---

src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
src/CommunityToolkit.Maui.Core/Primitives/Defaults/AlertDefaults.shared.cs
src/CommunityToolkit.Maui.Core/Primitives/Defaults/AvatarViewDefaults.shared.cs
src/CommunityToolkit.Maui.Core/Primitives/Defaults/DrawingViewDefaults.shared.cs
src/CommunityToolkit.Maui.Core/Primitives/Defaults/ImageTouchBehaviorDefaults.shared.cs
src/CommunityToolkit.Maui.Core/Primitives/Defaults/RatingViewDefaults.shared.cs
src/CommunityToolkit.Maui.Core/Primitives/Defaults/TouchBehaviorDefaults.shared.cs

This PR adds `<InternalsVisibleTo Include="CommunityToolkit.Maui"/>` to `CommunityToolkit.Maui.Core.csproj`
This PR was created in support of #1581 to allow us to avoid duplicating internal code in both `CommunityToolkit.Maui` and `CommunityToolkit.Maui.Core`.
Direct link to code review conversation: https://github.com/CommunityToolkit/Maui/pull/1581/files/d6be9aa2a69235b93c767950320d672801381f72#diff-cf2cf0700afaffb4d539f76209659b6a99b97459af586d68507410fd166a1a99
This PR also removes the `[EditorBrowsable(EditorBrowsableState.Never)]` from unsupported/undocumented `Defaults` constants and reduces each class's scope from `public` to `internal`

Add `<InternalsVisibleTo Include="CommunityToolkit.Maui"/>` to `CommunityToolkit.Maui.Core.csproj`

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs

- Bug fix
This change is for something that was missed when migrating to dotnet 9.x. The manual disconnect of media element is no longer needed. It was removed from sample app but was missed in popup. This removes it from sample app. An update to docs is going to be required.
- Fixes #2653
This fix will remove manually disconnecting the handler which is not longer needed. It is now handled by dotnet maui directly.

Remove MediaElement Handler disconnect in popups

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/PopupsPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CsharpBindingPopupViewModel.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/PopupsViewModel.cs
samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml
samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml.cs
src/CommunityToolkit.Maui.Core/Interfaces/IPopupResult.shared.cs
src/CommunityToolkit.Maui.UnitTests/BaseHandlerTest.cs
src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
src/CommunityToolkit.Maui.UnitTests/Extensions/PopupExtensionsTests.cs
src/CommunityToolkit.Maui.UnitTests/Mocks/MockPage.cs
src/CommunityToolkit.Maui.UnitTests/Services/PopupServiceTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupPageTests.cs
src/CommunityToolkit.Maui/Extensions/PopupExtensions.shared.cs
src/CommunityToolkit.Maui/Interfaces/IPopupService.shared.cs
src/CommunityToolkit.Maui/Services/PopupService.shared.cs
src/CommunityToolkit.Maui/Views/Popup/PopupPage.shared.cs

This PR augments https://github.com/CommunityToolkit/Maui/pull/1581, adding support for `Shell` and `IQueryAttributable`. I.e., this PR will be merged into the open [PopupV2 PR](https://github.com/CommunityToolkit/Maui/pull/1581), not the `main` branch.
Specifically, this PR was created in response to @bijington's review noting that users will no longer be able to pass data from ViewModel to ViewModel after removing the `onPresenting` parameter: https://github.com/CommunityToolkit/Maui/pull/1581#discussion_r2079810384
This PR is currently in Draft because it still requires Unit Tests.
I updated `SimplePopup` and `CsharpBindingPopup` to demonstrate using `IQueryAttributable` in the Sample App.

Add Support for Shell + `IQueryAttributable` for PopupV2

---

Directory.Build.props
src/CommunityToolkit.Maui.Analyzers/CommunityToolkit.Maui.Analyzers.csproj
src/CommunityToolkit.Maui.Camera.Analyzers/CommunityToolkit.Maui.Camera.Analyzers.csproj
src/CommunityToolkit.Maui.MediaElement.Analyzers/CommunityToolkit.Maui.MediaElement.Analyzers.csproj
src/CommunityToolkit.Maui.SourceGenerators.Internal/CommunityToolkit.Maui.SourceGenerators.Internal.csproj
src/CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.csproj

This PR adds `RS1038` to `<WarningsAsErrors>` and replaces `Microsoft.CodeAnalysis.CSharp.Workspaces` -> `Microsoft.CodeAnalysis.CSharp`
Link to RS1038 Docs:
https://github.com/dotnet/roslyn-analyzers/blob/main/docs/rules/RS1038.md
Link to Compiler Warnings seen in `CommunityToolkit.Maui`: https://github.com/CommunityToolkit/Maui/actions/runs/15263232470/job/42928522628#step:14:61
> Warning: D:\a\Maui\Maui\src\CommunityToolkit.Maui.Analyzers\UseCommunityToolkitInitializationAnalyzer.cs(9,2): warning RS1038: This compiler extension should not be implemented in an assembly containing a reference to Microsoft.CodeAnalysis.Workspaces. The Microsoft.CodeAnalysis.Workspaces assembly is not provided during command line compilation scenarios, so references to it could cause the compiler extension …

Fix RS1038 Warning: Compiler extensions should be implemented in assemblies with compiler-provided references

---

src/CommunityToolkit.Maui/Extensions/ServiceCollectionExtensions.shared.cs

…allowed
Restricts the types allowed into `AddXPopup` extension methods to prevent `ContentPage` from being passed in.
- Fixes #2713

Restrict AddPopup extensions to View to avoid ContentPage from being allowed

---

samples/CommunityToolkit.Maui.Sample/Platforms/Windows/Package.appxmanifest
samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/SpeechToTextViewModel.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/OfflineSpeechToTextImplementation.windows.cs
src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.windows.cs

Speech Recognition Windows Ensure unsubscribe from events on Stop Recording

Speech Recognition Windows Ensure unsubscribe from events on Stop Recording

---

src/CommunityToolkit.Maui.Camera/Interfaces/ICameraView.shared.cs
src/CommunityToolkit.Maui.Camera/Views/CameraView.shared.cs

**API Change**
This PR updates `ICameraView.CaptureImage()` to return the `Stream` captured by the camera:
```cs
// Previous (Existing) API
ValueTask CaptureImage(CancellationToken token);
```
to
```cs
// Updated API
Task<Stream> CaptureImage(CancellationToken token);
```
**Developer Experience Improvement**
This improves the developer experience, allowing devs to retrieve the image directly from the method, whereas the current/previous experience required them to subscribe to `CameraView.MediaCaptured`:
```cs
// Previous (Existing) Developer Experience
public partial class CameraPage : Content
{
public CameraPage()
{
InitializeComponent();
cameraView.MediaCaptured += HandleMediaCaptured;
cameraView.MediaCaptureFailed += HandleMediaCaptureFailed
}
async void CaptureButtonTapped(object? …
```

Return Camera Image (`Stream`) from `ICameraView.CaptureImage()`

---

src/CommunityToolkit.Maui.UnitTests/BaseHandlerTest.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/PopupExtensionsTests.cs
src/CommunityToolkit.Maui.UnitTests/Services/PopupServiceTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupPageTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupTests.cs
src/CommunityToolkit.Maui/Primitives/Defaults/PopupDefaults.shared.cs
src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
src/CommunityToolkit.Maui/Views/Popup/PopupPage.shared.cs

ShowPopupAsync will now correctly return once the popup is closed under heavy garbage collection

---

.github/workflows/dotnet-build.yml

Publish main to github nuget

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs

Fix sample app MediaElement Popup to use a `URL` for MetadataArtworkUrl. Set `Width` and `Height` for Popup MediaElement so that you can click outside popup to close it. 
This fixes a bug where the artwork URL was set to string and not a url and the popup cannot be tapped outside popup as it takes the full screen in Windows.

Fix MediaElement in Sample App

---

samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/ComplexPopupViewModel.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/AppBuilderExtensionsTests.cs
src/CommunityToolkit.Maui.UnitTests/Extensions/PopupExtensionsTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/DefaultPopupOptionsSettingsTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupOptionsTests.cs
src/CommunityToolkit.Maui.UnitTests/Views/Popup/PopupPageTests.cs
src/CommunityToolkit.Maui/Options.cs
src/CommunityToolkit.Maui/Primitives/DefaultPopupOptionsSettings.cs
src/CommunityToolkit.Maui/Views/Popup/PopupPage.shared.cs

This PR introduces a workaround to swallow any touches on our internal Border control to avoid the touches rippling through to the background BoxView.
- Fixes #2795
This is more of a workaround than a fix but it does solve the issue for now

Prevent Popup From Being Dismissed when Tapped Inside Popup

---

src/CommunityToolkit.Maui.UnitTests/Converters/ListToStringConverterTests.cs
src/CommunityToolkit.Maui/Converters/TextCaseConverter.shared.cs

This PR adds missing unit test coverage for the `ListToStringConverter` when handling whitespace-only strings.
The `ListToStringConverter` correctly filters out strings that are null, empty, or contain only whitespace characters (as implemented in line 40 of the converter), but there were no unit tests verifying this behavior for whitespace-only strings like spaces, tabs, and newlines.
**Changes:**
- Added 3 new test cases to verify whitespace-only strings are properly filtered out
- Covers spaces, tabs, and newlines as edge cases
- Improves test coverage without changing functionality
**Test Cases Added:**
- `["A", "   ", "C"]` → `"A,C"` (spaces)
- `["A", "\t", "C"]` → `"A,C"` (tabs)  
- `["A", "\n", "C"]` → `"A,C"` (newlines)
- Fixes # (This is a test coverage improvement, not a bug …

Refactor TextCaseConverter and enhance ListToStringConverterTests

---

samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsInRangeConverterPage.cs

Fix typo: `Commpare` -> `Compare`

Fix typo in the example label text on IsInRangeConverterPage
