CommunityToolkit/Maui

- src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
- src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
This PR updates the NuGet Packages for Code Coverage and Unit Testing
> Update NuGet Packages

- .github/ISSUE_TEMPLATE/bug_report_template.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/proposal_template.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix_template.md
- .github/PULL_REQUEST_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE/new_feature_template.md
- README.md
This Pull Request adds the following:
- Adds the New Feature Workflow the README
- Adds Bug Report Template
- Adds Proposal Template
> Add Proposal Workflow

- samples/CommunityToolkit.Maui.Sample/Pages/Converters/EqualConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/EqualsConverterViewModel.cs
[#60 EqualConverter](https://github.com/CommunityToolkit/Maui/issues/60)
Created a sample page for the EqualConverter.
> Create a sample for the EqualConverter

- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IndexToArrayItemConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IndexToArrayItemConverterPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/IndexToArrayItemConverterViewModel.cs
#62 Created a sample for the IndexToArrayItemConverter.
**Convert**: You can increment the index with a stepper control to select the next or previous item in a CollectionView control. 
**ConvertBack**: Select an item from the CollectionView control to change the selected inde
x.
> Created a sample for  the IndexToArrayItemConverter

- .github/ISSUE_TEMPLATE/config.yml
Nothing
Adds a link over to the new MauiCompat template
> Link to the new maui-compat template

- src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.windows.cs
- src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
Snackbar for Windows uses a package for Uwp instead of WinUI.
> Update Snackbar to use WinUI package

- src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
- src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
- Fixes #
On project reorganization PR we forgot to add the WinUI reference, so I'm doing it right now❣
> [🔥Hot Fix🔥] Adding WinUI reference

- azure-pipelines.yml
- src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
This Pull Request enables the publishing of our new NuGet Package, [`CommunityToolkit.Maui.Core`](https://github.com/CommunityToolkit/Maui/issues/213).
- `CommunityToolkit.Maui.Core.csproj`
- Remove `<IsPackable>false</IsPackable>`
- `azure-pipelines.yml`
- `build_windows`
- Add `Build and Pack CommunityToolkit.Maui.Core` Step
- `build_macOS`
- Add `Pack CommunityToolkit.Maui.Core NuGet` Step
> Publish `CommunityToolkit.Maui.Core` NuGet Package

- CONTRIBUTING.md
- README.md
Added in the missing docs repo url to `ReadMe` and `CONTRIBUTING` files
> Added new docs repo url

- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/ItemSelectedEventArgsConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/ItemSelectedEventArgsConverterPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ItemSelectedEventArgsConverterViewModel.cs
- src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
Adds a sample for the ItemSelectedEventArgsConverter to the sample app. 
Since this is purely the implementation of the sample, there are no additional tests or documentation.
- Fixes #67 
The sample does not currently render correctly in Android, although I suspect this may be related to https://github.com/dotnet/maui/issues/4007. More than happy to take guidance on how to resolve this, however.
> Implement ItemSelectedEventArgsConverter sample

- azure-pipelines.yml
> Remove duplicated steps from azure pipeline

- azure-pipelines.yml
remove the output dir, because VS overwrites the previous target framework
- Fixes https://github.com/CommunityToolkit/Maui/issues/268
> Fix SupportedOSPlatform and TargetPlatform

- .runsettings
- azure-pipelines.yml
- nuget.config
- samples/CommunityToolkit.Maui.Sample/App.xaml
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- samples/CommunityToolkit.Maui.Sample/Platforms/Android/MainActivity.cs
- samples/CommunityToolkit.Maui.Sample/Platforms/Windows/App.xaml.cs
- samples/CommunityToolkit.Maui.Sample/Platforms/Windows/Package.appxmanifest
- src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
- src/CommunityToolkit.Maui.UnitTests/Extensions/ColorConversionExtensions_Tests.cs
> Fix vulnerability check, fix code coverage, add some tests

- samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/MaskedBehaviorPage.xaml
- src/CommunityToolkit.Maui.UnitTests/Behaviors/MaskedBehavior_Tests.cs
- src/CommunityToolkit.Maui/Behaviors/BaseBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/MaxLengthReachedBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/UserStoppedTypingBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/Validators/ValidationBehavior.shared.cs
This PR implements the Unit Tests for #46 
- Fixes #46 
I also updated `BaseBehavior.OnViewPropertyChanged` to use `TView`:
**Updated**
```cs
protected virtual void OnViewPropertyChanged(TView sender, PropertyChangedEventArgs e)
{
}
```
**Previous**
```cs
protected virtual void OnViewPropertyChanged(object? sender, PropertyChangedEventArgs e)
{
}
```
> Add `MaskedBehavor` Unit Tests

- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
Removes an extraneous `services.AddTransient<AlertsGalleryPage>();`
- Fixes #
> Remove extraneous page registration from sample

- azure-pipelines.yml
- global.json
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Models/PopupSize.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
- src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
- src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.android.cs
- src/CommunityToolkit.Maui/Alerts/Toast/Toast.android.cs
- src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs
> Update to .NET MAUI RC1

- src/CommunityToolkit.Maui.Core/Extensions/ColorConversionExtensions.shared.cs
Fixes mistakes in the xml docs discovered when writing up docs.
> fix xml docs for color extensions

- samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/StateToBooleanConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/StateToBooleanConverterPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/StateToBooleanConverterViewModel.cs
This PR adds the sample for StateToBooleanConverter
- Fixes #74
> Added sample for StateToBooleanConverter

- samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Base/BasePage.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsNotNullConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsNotNullConverterPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsNullConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsNullConverterPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/ConvertersGalleryViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/IsNotNullConverterViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/IsNullConverterViewModel.cs
- src/CommunityToolkit.Maui.UnitTests/Converters/IsNotNullConverter_Tests.cs
- src/CommunityToolkit.Maui.UnitTests/Converters/IsNullConverter_Tests.cs
- src/CommunityToolkit.Maui/Converters/IsNotNullConverter.shared.cs
- src/CommunityToolkit.Maui/Converters/IsNullConverter.shared.cs
2 new converters - 
- IsNotNullConverter 
- IsNullConverter 
- #306
> IsNull / IsNotNull Converters

- src/CommunityToolkit.Maui/AppBuilderExtensions.shared.cs
> Fix popup handler was not found

- src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/Validators/RequiredStringValidationBehavior.shared.cs
Improves xml documentation for the `MaskedBehavior`.
> Improve xml docs

- samples/CommunityToolkit.Maui.Sample/Pages/Converters/ItemTappedEventArgsConverterPage.xaml
Simple update to text in sample screen as discovered in https://github.com/MicrosoftDocs/CommunityToolkit/pull/79/files
> Fix item tapped converter sample text

- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
- src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
> Update to RC2

- samples/CommunityToolkit.Maui.Sample/Pages/Converters/MultiConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/MultiConverterViewModel.cs
Added an example to the Sample app for MultiConverter.
#72 
This has been tested on Windows.
This is my first PR, please be gentle!
> Added MultiConverter Sample

- azure-pipelines.yml
- global.json
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
- src/CommunityToolkit.Maui.UnitTests/Extensions/BackgroundColorTo_Tests.cs
- src/CommunityToolkit.Maui.UnitTests/Extensions/TextColorTo_Tests.cs
> Update to .NET MAUI RC3

- samples/CommunityToolkit.Maui.Sample/Pages/Converters/MathExpressionConverterPage.xaml
- samples/CommunityToolkit.Maui.Sample/ViewModels/Converters/MathExpressionConverterViewModel.cs
Added a sample for MathExpressionConverter to the Sample app.
#71 
- Fixes #
Tested on Windows and Android platforms.
> Added MathExpressionConverter sample

- src/CommunityToolkit.Maui.Core/Handlers/DrawingView/DrawingViewHandler.shared.cs
- src/CommunityToolkit.Maui/Views/DrawingView/DrawingView.shared.cs
https://github.com/dotnet/maui/issues/3604
> DrawingView DisconnectHandler

- 6.0.312.json
- azure-pipelines.yml
- samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- src/CommunityToolkit.Maui.Core/CommunityToolkit.Maui.Core.csproj
- src/CommunityToolkit.Maui/CommunityToolkit.Maui.csproj
> Pin .NET MAUI Version to v6.0.312

- samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/SelectAllTextBehaviorPage.xaml
- src/CommunityToolkit.Maui.SourceGenerators/Diagnostics/TextColorToDiagnostic.cs
- src/CommunityToolkit.Maui.SourceGenerators/Extensions/NamespaceSymbolExtensions.cs
- src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
- src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
- src/CommunityToolkit.Maui/Views/WrapperControl.windows.cs
Replace Frame with Border, 
Fix typos
- Fixes #475
> #475 Fix Sample freezes on SelectAllTextBehaviorPage, fix typos

- src/CommunityToolkit.Maui.Core/Views/Alert/AlertView.macios.cs
- src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.macios.cs
- src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.windows.cs
Fix NRE exceptions
- Fixes #500 
- Fixes NRE KeyWindow is null
> Fix #500 Color is Null. Fix KeyWindow not correctly calculated

- .github/ISSUE_TEMPLATE/bug_report_template.md
Bug Report Form to ask user  attach files:
See in action: https://github.com/VladislavAntonyuk/TemplateSample
> Bug Report Form

- src/CommunityToolkit.Maui.Core/Handlers/Popup/PopupHandler.macios.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.windows.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs
- src/CommunityToolkit.Maui/Behaviors/AnimationBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/ImpliedOrderGridBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/IconTintColor/IconTintColorBehavior.android.cs
- src/CommunityToolkit.Maui/Behaviors/Validators/EmailValidationBehavior.shared.cs
- src/CommunityToolkit.Maui/Converters/DoubleToIntConverter.shared.cs
- src/CommunityToolkit.Maui/Converters/EnumToIntConverter.shared.cs
- src/CommunityToolkit.Maui/Converters/IndexToArrayItemConverter.shared.cs
- src/CommunityToolkit.Maui/Converters/MathExpressionConverter/MultiMathExpressionConverter.shared.cs
- src/CommunityToolkit.Maui/Converters/StringToListConverter.shared.cs
- src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs
- src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.net.cs
- src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs
> CODE RUB: Simple Exception Syntax Error.

- src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs
Removed the `if` that didn't allow the change of that configuration.
- Fixes #660
> Fixed light dismiss on android

- samples/CommunityToolkit.Maui.Sample/Pages/Alerts/SnackbarPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Alerts/ToastPage.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/ButtonPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/CsharpBindingPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/MultipleButtonPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/NoOutsideTapDismissPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/OpenedEventSimplePopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/ReturnResultPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/SimplePopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/ToggleSizePopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/TransparentPopup.xaml
- samples/CommunityToolkit.Maui.Sample/Views/Popups/XamlBindingPopup.xaml
- src/CommunityToolkit.Maui.UnitTests/Mocks/AnimationExtensions.cs
- src/CommunityToolkit.Maui/Behaviors/MaskedBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/Validators/ValidationBehavior.shared.cs
Replaces UWP with WInUI.  Implement IDisposable to fix build issues
> Remove obsolete APIs,  Implement IDisposable

- samples/CommunityToolkit.Maui.Sample/Pages/Alerts/SnackbarPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Alerts/SnackbarPage.xaml.cs
- src/CommunityToolkit.Maui/Alerts/Snackbar/Snackbar.android.cs
Fix calculation of parent view of Snackbar. Calculate action button height to apply margin for modal window
- Fixes #642
> 642 Fix Calculation of `Snackbar` Parent View

- samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml
> fix: Removed wrong attributes on ExpanderPage.

- src/CommunityToolkit.Maui/ImageSources/GravatarImageSource.shared.cs
Removed the field `TokenSource` as it is never assigned.
https://github.com/CommunityToolkit/Maui/discussions/680#discussioncomment-4597219
- Fixes https://github.com/CommunityToolkit/Maui/discussions/680#discussioncomment-4597219
No additional samples, tests or documentation required.
> TokenSource field is never assigned

- README.md
- src/CommunityToolkit.Maui/ReadMe.txt
This PR updates `ReadMe.txt`'s code snippet to match the .NET MAUI Templates included in Visual Studio.
- Fixes #868
> Update `ReadMe.txt` Code Snippet To Match the .NET MAUI Templates

- samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/CharactersValidationBehaviorPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/CharactersValidationBehaviorPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/CharactersValidationBehaviorViewModel.cs
> Fix CharactersValidationBehavior Bindings missing #474

- src/CommunityToolkit.Maui/Extensions/ToastNotificationExtensions.windows.cs
Continuation of https://github.com/CommunityToolkit/Maui/pull/900
> Make ToastNotificationExtensions internal

- samples/CommunityToolkit.Maui.Sample/Pages/Layouts/UniformItemsLayoutPage.xaml
- src/CommunityToolkit.Maui.Core/Layouts/UniformItemsLayoutManager.shared.cs
Measure items before arrange
- Fixes #902
> Fix Multiple StackLayouts inside of UniformItemsLayout do not show up

- src/CommunityToolkit.Maui.UnitTests/Converters/DateTimeOffsetConverterTests.cs
- src/CommunityToolkit.Maui/Converters/DateTimeOffsetConverter.shared.cs
I always have 1 failed test where Offset doesn't match (Expected +02:00, but Received +03:00).
This PR fixes the issue
- Fixes [UTC offset of local dateTime does not match the offset argument](https://stackoverflow.com/questions/36255821/datetimeoffset-error-utc-offset-of-local-datetime-does-not-match-the-offset-arg)
> DateTimeOffsetConverter fix ArgumentException

- samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/ShowPopupInOnAppearingPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/ShowPopupInOnAppearingPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/ShowPopupInOnAppearingPageViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
- src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
- src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs
Introduces the approach of deferring a `ShowPopup` and `ShowPopupAsync` call to the `OnNavigatedTo` event if the `IsPlatformEnabled` flag is `false`. This matches how .NET MAUI provides similar support for things like `DisplayAlert`, etc.
- Fixes #822
- Fixes #693
Possibly helps
- #810 **but this is untested**
> Postpone popup show until platform is ready

- samples/CommunityToolkit.Maui.Sample/Pages/Base/BaseGalleryPage.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Converters/IsInRangeConverterPage.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
This PR implements the new [TypedBindings](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/markup/extensions/bindable-object-extensions#two-way-binding) feature introduced in [CommunityToolkit.Maui.Markup v3.0.0](https://github.com/CommunityToolkit/Maui.Markup/releases/tag/3.0.0).
Typed Bindings (also known as "Compiled Bindings") revolutionize the way we make bindings using [CommunityToolkit.Maui.Markup](https://learn.microsoft.com/dotnet/communitytoolkit/maui/markup/markup):
Learn more 
[✅ Official Docs](https://learn.microsoft.com/dotnet/communitytoolkit/maui/markup/extensions/bindable-object-extensions#bind)
[✅ MauiConverter Sample App](https://github.com/brminnick/MauiConverter/blob/b85d15cbc68e84dbeb7eddc91f21b853b2cacd88/src/MauiConverter/Pages/ConversionPage.cs) …
> [Sample App] Implement Typed Bindings

- src/CommunityToolkit.Maui.MediaElement/CommunityToolkit.Maui.MediaElement.csproj
Updates MediaElement for Android to the latest Exoplayer bindings version
- Closes #970 
- Closes #971
> Update ExoPlayer binding dependencies

- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
- src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.net.cs
- src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.shared.cs
- src/CommunityToolkit.Maui.MediaElement/Interfaces/IMediaElement.cs
- src/CommunityToolkit.Maui.MediaElement/MediaElement.shared.cs
- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.android.cs
- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.macios.cs
- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.shared.cs
- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.tizen.cs
- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Implements muting functionality for `MediaElement`
- Fixes #950
> Implement Mediaelement ShouldMute

- samples/CommunityToolkit.Maui.Sample/ViewModels/Essentials/FileSaverViewModel.cs
- src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs
- src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.windows.cs
> Fix FileSaver exception {"The parameter is incorrect.\r\n"}

- src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
- src/CommunityToolkit.Maui.Core/Essentials/FolderPicker/FolderPickerImplementation.android.cs
> No need to create choose intent

- samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Expander/ExpanderPageCS.cs
This PR adds a `Button` to the `Expander` sample. 
I added this when debugging #1216 to demonstrate that a `Button` inside an `Expander` is indeed clickable
- Fixes https://github.com/CommunityToolkit/Maui/issues/1216
This PR doesn't necessarily add much value, but since I wrote the code to validate #1216, I figured we could keep the code and add it to the Sample app
> [Sample App] Add Button to Expander Sample

- src/CommunityToolkit.Maui.Core/Views/DrawingView/Service/DrawingViewService.android.cs
> Fix Android DrawingView background image color

- samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/Bounds.shared.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/Center.shared.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/EventIdentifier.shared.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/EventMessage.shared.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/InfoWindow.shared.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs
Implements `MapClicked` for the Windows map. Also restructures how the events are handled to be more robust and future proof. Can probably be optimized further, but this should be a good starting point.
- Fixes #1268
> Implement MapClicked

- CONTRIBUTING.md
- src/CommunityToolkit.Maui.Core/Essentials/Badge/Android/DefaultBadgeProvider.android.cs
- src/CommunityToolkit.Maui.Core/Essentials/Badge/BadgeImplementation.macios.cs
- src/CommunityToolkit.Maui.Core/Platform/StatusBar/StatusBar.android.cs
- src/CommunityToolkit.Maui.Core/Views/DrawingView/PlatformView/MauiDrawingView.windows.cs
- src/CommunityToolkit.Maui.SourceGenerators/Generators/TextColorToGenerator.cs
- src/CommunityToolkit.Maui.UnitTests/Layouts/StateContainerTests.cs
- src/CommunityToolkit.Maui/Behaviors/AnimationBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/BaseBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/ImpliedOrderGridBehavior.shared.cs
- src/CommunityToolkit.Maui/Behaviors/Validators/ValidationBehavior.shared.cs
- src/CommunityToolkit.Maui/Converters/BaseConverter.shared.cs
- src/CommunityToolkit.Maui/Extensions/ColorAnimationExtensions.shared.cs
- src/CommunityToolkit.Maui/Extensions/HttpClientExtensions.shared.cs
Changing all the `Debug.WriteLine` calls to `Trace.WriteLine`.
- Fixes #1310
> ♻️ Replaced all Debug.WriteLine for Trace.WriteLine

- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Maps/MapsPinsPage.xaml.cs
- src/CommunityToolkit.Maui.Maps/Handler/Map/MapHandler.Windows.cs
HideInfoWindow if args is set to true
Methods SendMarkerClick/SendInfoWindowClick return a boolean parameter, indicating if the info window should be closed.
> WindowsMaps HideInfoWindow

- src/CommunityToolkit.Maui.MediaElement/Views/MediaManager.windows.cs
Allow updating position when in Paused/Stopped state
- Fixes #1313
> Allow position update from paused/stopped state

- src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/SafeFireAndForgotExtensions.cs
- src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.android.cs
- src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.ios.cs
- src/CommunityToolkit.Maui/Behaviors/PlatformBehaviors/Touch/TouchBehavior.shared.cs
I added an first implementation for iOS, ported from XCT. 
Moreover, I fixed some issues with the Android behavior.
For me, native animations now work on both platforms as intended (like in XCT).
> Touch effect maui

- src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs
In Create PageHandler a Page is created without setting the Parent, this causes some issues because the Page has no Parent and therefore no Gestures are initialized
Because this is only an issue on iOS I don't know how to create a device specific test. Maybe a Sample is needed.
- Fixes https://github.com/dotnet/maui/issues/15760
> Fix Gestures on Popup on ios

- src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs
This PR reverts the change added on #1343 since that PR didn't close any open issues and the issue it claims to fix is already fixed in previous PRs.
- Fixes #
> Reverted change add in #1343

- samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/CustomSizeAndPositionPopupPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/Popup/CustomSizeAndPositionPopupPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/Popup/CustomSizeAndPositionPopupViewModel.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.tizen.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.android.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.macios.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/PopupExtensions.windows.cs
This PR corrects the display position of Popup so that it is displayed as intended on Windows when FlowDirection is specified for Popup Content.
Change the display position calculation formula as shown below depending on the FlowDirection value of Popup Content.
[src\CommunityToolkit.Maui.Core\Views\Popup\PopupExtensions.windows.cs]
public static void SetLayout(this Popup mauiPopup, IPopup popup, IMauiContext? mauiContext)
{
ArgumentNullException.ThrowIfNull(mauiContext);
ArgumentNullException.ThrowIfNull(popup.Content);
var popupParent = mauiContext.GetPlatformWindow();
popup.Content.Measure(double.PositiveInfinity, double.PositiveInfinity);
var contentSize = popup.Content.ToPlatform(mauiContext).DesiredSize;
var popupParentFrame = popupParent.Bounds;
var hSign = …
> Add consideration of FlowDirection

- src/CommunityToolkit.Maui.Core/Essentials/SpeechToText/SpeechToTextImplementation.android.cs
> Fixes Speech recognizer locale was not ignored on Android #1436

- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementPage.xaml.cs
- Bug fix
Change Media Element URL for HLS stream in Sample app
- Fixes #1570 
This PR will fix Media Element URL cannot be resolved in all devices for HLS stream in Sample app.
> Change HLS URL

- samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/AnimationBehaviorPage.xaml
- samples/CommunityToolkit.Maui.Sample/ViewModels/Behaviors/AnimationBehaviorViewModel.cs
- Fixes #1572
In truth this doesn't actually fix anything but it does provide a sample on how the `AnimateCommand` can be used.
> Add sample to trigger an animation using the AnimateCommand

- Directory.Build.props
- azure-pipelines.yml
- global.json
This PR Increases the dependencies for the following NuGet Packages:
- Microsoft.Maui.Controls
- Microsoft.Maui.Controls.Compatability
- Microsoft.Maui.Core
- Microsoft.Maui.Maps
- Microsoft.Maui.Essentials
> Increase to latest MauiPackageVersion, v8.0.14

- azure-pipelines.yml
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- src/CommunityToolkit.Maui.Analyzers.CodeFixes/CommunityToolkit.Maui.Analyzers.CodeFixes.csproj
- src/CommunityToolkit.Maui.Analyzers.UnitTests/CommunityToolkit.Maui.Analyzers.UnitTests.csproj
- src/CommunityToolkit.Maui.Analyzers/CommunityToolkit.Maui.Analyzers.csproj
- src/CommunityToolkit.Maui.MediaElement.Analyzers.CodeFixes/CommunityToolkit.Maui.MediaElement.Analyzers.CodeFixes.csproj
- src/CommunityToolkit.Maui.MediaElement.Analyzers/CommunityToolkit.Maui.MediaElement.Analyzers.csproj
- src/CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.csproj
- src/CommunityToolkit.Maui.UnitTests/Behaviors/AnimationBehaviorTests.cs
- src/CommunityToolkit.Maui.UnitTests/CommunityToolkit.Maui.UnitTests.csproj
This PR updates all pending NuGet Package updates in this library.
It looks like Dependabot is having errors not related to us and we'll have to manually update our NuGet Packages for a bit.
> [Housekeeping] Update NuGet Packages

- src/CommunityToolkit.Maui.Camera/CommunityToolkit.Maui.Camera.csproj
- src/CommunityToolkit.Maui.Camera/Interfaces/IAsynchronouseHandler.cs
- src/CommunityToolkit.Maui.Camera/Interfaces/ICameraView.shared.cs
- src/CommunityToolkit.Maui.Camera/Views/CameraView.shared.cs
- src/CommunityToolkit.Maui/Extensions/ValueConverterExtension.shared.cs
This PR removes the `CommunityToolkit.Maui.Core` dependency from `CommunityToolkit.Maui.Camera`
This duplicates the `IAsynchronousHandler` between `CommunityToolkit.Maui.Core` and `CommunityToolkit.Maui.Camera`.
> Remove `CommunityToolkit.Maui.Core` dependency from `CommunityToolkit.Maui.Camera`

- src/CommunityToolkit.Maui.Camera/CameraManager.android.cs
> Remove ArrayPool usage for now to avoid BufferUnderflow

- samples/CommunityToolkit.Maui.Sample/AppShell.xaml.cs
- samples/CommunityToolkit.Maui.Sample/CommunityToolkit.Maui.Sample.csproj
- samples/CommunityToolkit.Maui.Sample/MauiProgram.cs
- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementCollectionViewPage.xaml
- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementCollectionViewPage.xaml.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/MediaElementCollectionViewViewModel.cs
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/ViewsGalleryViewModel.cs
Add `CollectionView` to Samples app for Media Element.
Add support for  `CollectionView` to Samples app for `MediaElement`
> Add CollectionView sample to MediaElement

- src/CommunityToolkit.Maui/Views/Popup/Popup.shared.cs
> Only set the popup contents parent if it hasn't already been set before

- samples/CommunityToolkit.Maui.Sample/Pages/Views/MediaElement/MediaElementCarouselViewPage.xaml
This PR updates `MediaElementCarouselViewPage.xaml` to reproduce issue noted in Issue 2246.
This sample does not fix Issue 2246, rather it adds a reproduction sample to help the future bug fix for Issue 2246.
> [Sample App] Add Second CarouselView to `MediaElementCarouselViewPage.xaml`

- src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.android.cs
- src/CommunityToolkit.Maui.Core/Essentials/FileSaver/FileSaverImplementation.shared.cs
> Fix FileSaver Progress

- azure-pipelines.yml
- samples/CommunityToolkit.Maui.Sample/ViewModels/Views/CameraView/CameraViewViewModel.cs
- src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs
- Bug fix
Fix MVVM Observable Properties error: mvvmtk0045. More about this can be found here: https://learn.microsoft.com/en-gb/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0045
- Fixes #2398
This fixes a small bug in Samples app.
> Fix ObservableProperties error: mvvmtk0045

- .github/workflows/dotnet-build.yml
> [Housekeeping] Improve Code Coverage Report

- Directory.Build.props
We use some internal methods from .NET MAUI, and in 9.0.50 they changed how `AddLogicalChild` works causing an crash when devs use our package and have Maui.Controls on version 9.0.50.
- Fixes #2583
> Bump MauiPackageVersion to 9.0.50

- .github/copilot-instructions.md
Added sections on collection initializers and file-scoped namespaces in `copilot-instructions.md`, including examples and links to relevant documentation to improve code clarity and reduce verbosity.
- Fixes #
Update copilot to `Use collection initializers or expressions`
> Enhance copilot instructions for C# best practices
